# SPDX-FileCopyrightText: 2020 20kdc
# SPDX-FileCopyrightText: 2020 AJCM-git
# SPDX-FileCopyrightText: 2020 FL-OZ
# SPDX-FileCopyrightText: 2020 Hugo Laloge
# SPDX-FileCopyrightText: 2020 Peter Wedder
# SPDX-FileCopyrightText: 2020 ike709
# SPDX-FileCopyrightText: 2021 Elijahrane
# SPDX-FileCopyrightText: 2021 Paul Ritter
# SPDX-FileCopyrightText: 2021 Swept
# SPDX-FileCopyrightText: 2021 Vera Aguilera Puerto
# SPDX-FileCopyrightText: 2022 Kara
# SPDX-FileCopyrightText: 2022 Leon Friedrich
# SPDX-FileCopyrightText: 2022 Moony
# SPDX-FileCopyrightText: 2022 Morber
# SPDX-FileCopyrightText: 2022 Pieter-Jan Briers
# SPDX-FileCopyrightText: 2022 Rane
# SPDX-FileCopyrightText: 2022 Sissel
# SPDX-FileCopyrightText: 2022 Veritius
# SPDX-FileCopyrightText: 2023 Chief-Engineer
# SPDX-FileCopyrightText: 2023 Colin-Tel
# SPDX-FileCopyrightText: 2023 Debug
# SPDX-FileCopyrightText: 2023 DrSmugleaf
# SPDX-FileCopyrightText: 2023 Emisse
# SPDX-FileCopyrightText: 2023 Fluffiest Floofers
# SPDX-FileCopyrightText: 2023 Nemanja
# SPDX-FileCopyrightText: 2023 PHCodes
# SPDX-FileCopyrightText: 2023 PrPleGoo
# SPDX-FileCopyrightText: 2023 Velcroboy
# SPDX-FileCopyrightText: 2023 coolmankid12345
# SPDX-FileCopyrightText: 2023 lzk228
# SPDX-FileCopyrightText: 2023 randy10122
# SPDX-FileCopyrightText: 2023 rosieposie
# SPDX-FileCopyrightText: 2024 DEATHB4DEFEAT
# SPDX-FileCopyrightText: 2024 Fansana
# SPDX-FileCopyrightText: 2024 FoxxoTrystan
# SPDX-FileCopyrightText: 2024 Nairod
# SPDX-FileCopyrightText: 2024 flyingkarii
# SPDX-FileCopyrightText: 2024 gluesniffler
# SPDX-FileCopyrightText: 2025 Eagle-0
# SPDX-FileCopyrightText: 2025 John Willis
# SPDX-FileCopyrightText: 2025 Sir Warock
# SPDX-FileCopyrightText: 2025 SixplyDev
# SPDX-FileCopyrightText: 2025 Skubman
# SPDX-FileCopyrightText: 2025 Timfa
# SPDX-FileCopyrightText: 2025 VMSolidus
# SPDX-FileCopyrightText: 2025 sleepyyapril
#
# SPDX-License-Identifier: AGPL-3.0-or-later AND MIT

# Best job.

- type: job
  id: ChiefMedicalOfficer
  name: job-name-cmo
  description: job-description-cmo
  playTimeTracker: JobChiefMedicalOfficer
  requirements:
    - !type:CharacterPlaytimeRequirement
      tracker: JobChemist
      min: 28800 # The Den - 8 hour
  weight: 10
  startingGear: CMOGear
  icon: "JobIconChiefMedicalOfficer"
  requireAdminNotify: true
  supervisors: job-supervisors-captain
  canBeAntag: false
  access:
  - Medical
  - Command
  - Maintenance
  - Chemistry
  - ChiefMedicalOfficer
  - Paramedic # DeltaV - Add Paramedic access
  - External # DeltaV - Paramedics need this access
  - Psychologist # DeltaV - Add Psychologist access
  - Cryogenics
  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant ]
  - !type:AddComponentSpecial
    components:
      - type: CommandStaff
  - !type:AddComponentSpecial
    components:
    - type: CPRTraining
  afterLoadoutSpecial:
  - !type:ModifyEnvirosuitSpecial
    charges: 8
  - !type:ModifyEnvirohelmSpecial
    powerCell: PowerCellMedium

- type: startingGear
  id: CMOGear
  subGear:
  - CMOPlasmamanGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitCMO
    back: ClothingBackpackCMOFilled
    shoes: ClothingShoesColorBrown
    id: CMOPDA
    ears: ClothingHeadsetAltMedical # Goobstation
  innerClothingSkirt: ClothingUniformJumpskirtCMO
  satchel: ClothingBackpackSatchelCMOFilled
  duffelbag: ClothingBackpackDuffelCMOFilled

- type: startingGear
  id: CMOPlasmamanGear
  parent: BasePlasmamanGear
  equipment:
    jumpsuit: ClothingUniformEnvirosuitCMO
    head: ClothingHeadEnvirohelmCMO
    gloves: ClothingHandsGlovesEnviroglovesWhite
