# SPDX-FileCopyrightText: 2023 DrSmugleaf
# SPDX-FileCopyrightText: 2023 Fluffiest Floofers
# SPDX-FileCopyrightText: 2023 LankLTE
# SPDX-FileCopyrightText: 2023 Nairod
# SPDX-FileCopyrightText: 2023 PrPleGoo
# SPDX-FileCopyrightText: 2023 Ubaser
# SPDX-FileCopyrightText: 2024 DEATHB4DEFEAT
# SPDX-FileCopyrightText: 2024 Fansana
# SPDX-FileCopyrightText: 2024 FoxxoTrystan
# SPDX-FileCopyrightText: 2024 VMSolidus
# SPDX-FileCopyrightText: 2024 gluesniffler
# SPDX-FileCopyrightText: 2025 Sir Warock
# SPDX-FileCopyrightText: 2025 Skubman
# SPDX-FileCopyrightText: 2025 Timfa
# SPDX-FileCopyrightText: 2025 sleepyyapril
# SPDX-FileCopyrightText: 2026 MajorMoth
#
# SPDX-License-Identifier: MIT AND AGPL-3.0-or-later

- type: job
  id: SeniorPhysician
  name: job-name-senior-physician
  description: job-description-senior-physician
  playTimeTracker: JobSeniorPhysician
  requirements:
    - !type:CharacterDepartmentTimeRequirement
      department: Medical
      min: 360000 # The Den: 100 hrs
  startingGear: SeniorPhysicianGear
  icon: "JobIconSeniorPhysician"
  supervisors: job-supervisors-cmo
  access:
  - Medical
  - Maintenance
  - Chemistry
  extendedAccess:
  - Paramedic # DEN: make accesses inline with MD
  special:
  - !type:AddComponentSpecial
    components:
    - type: CPRTraining

- type: startingGear
  id: SeniorPhysicianGear
  subGear:
  - DoctorPlasmamanGear
  equipment:
    head: ClothingHeadHatBeretSeniorPhysician
    jumpsuit: ClothingUniformJumpsuitSeniorPhysician
    back: ClothingBackpackMedicalFilled
    shoes: ClothingShoesColorBlack
    outerClothing: ClothingOuterCoatLabSeniorPhysician
    id: SeniorPhysicianPDA
    ears: ClothingHeadsetMedical
    belt: ClothingBeltMedicalFilled
  innerClothingSkirt: ClothingUniformJumpskirtSeniorPhysician
  satchel: ClothingBackpackSatchelMedicalFilled
  duffelbag: ClothingBackpackDuffelMedicalFilled
