# SPDX-FileCopyrightText: 2020 AJCM-git
# SPDX-FileCopyrightText: 2020 Swept
# SPDX-FileCopyrightText: 2021 Mith-randalf
# SPDX-FileCopyrightText: 2021 SweptWasTaken
# SPDX-FileCopyrightText: 2022 CommieFlowers
# SPDX-FileCopyrightText: 2022 Myctai
# SPDX-FileCopyrightText: 2022 Rinkashikachi
# SPDX-FileCopyrightText: 2022 Visne
# SPDX-FileCopyrightText: 2022 rolfero
# SPDX-FileCopyrightText: 2023 Flareguy
# SPDX-FileCopyrightText: 2023 LankLTE
# SPDX-FileCopyrightText: 2023 Maxtone
# SPDX-FileCopyrightText: 2023 Nairod
# SPDX-FileCopyrightText: 2023 Tad "Taddy" Johnson
# SPDX-FileCopyrightText: 2023 lapatison
# SPDX-FileCopyrightText: 2023 metalgearsloth
# SPDX-FileCopyrightText: 2024 Blu
# SPDX-FileCopyrightText: 2024 DEATHB4DEFEAT
# SPDX-FileCopyrightText: 2024 SimpleStation14
# SPDX-FileCopyrightText: 2024 VMSolidus
# SPDX-FileCopyrightText: 2025 Rosycup
# SPDX-FileCopyrightText: 2025 portfiend
# SPDX-FileCopyrightText: 2025 sleepyyapril
# SPDX-FileCopyrightText: 2025 themias
#
# SPDX-License-Identifier: MIT AND AGPL-3.0-or-later

- type: cargoProduct
  id: SecurityArmor
  icon:
    sprite: _DV/Clothing/OuterClothing/Armor/platecarrier.rsi # DeltaV - resprite
    state: icon
  product: CrateSecurityArmor
  cost: 800
  category: cargoproduct-category-name-security
  group: market
  excludedServers: [eternity] # DEN - Exclude dangerous prototypes from Eternity

- type: cargoProduct
  id: SecurityHelmet
  icon:
    sprite: _DV/Clothing/Head/Helmets/security.rsi # DeltaV - resprite
    state: icon
  product: CrateSecurityHelmet
  cost: 550
  category: cargoproduct-category-name-security
  group: market
  excludedServers: [eternity] # DEN - Exclude dangerous prototypes from Eternity

- type: cargoProduct
  id: SecurityNonLethal
  icon:
    sprite: Objects/Weapons/Guns/Battery/disabler.rsi
    state: base
  product: CrateSecurityNonlethal
  cost: 4000
  category: cargoproduct-category-name-security
  group: market
  excludedServers: [eternity] # DEN - Exclude dangerous prototypes from Eternity

- type: cargoProduct
  id: SecurityRiot
  icon:
    sprite: _DV/Clothing/OuterClothing/Armor/riot.rsi # DeltaV - resprite
    state: icon
  product: CrateSecurityRiot
  cost: 7500
  category: cargoproduct-category-name-security
  group: market
  excludedServers: [eternity] # DEN - Exclude dangerous prototypes from Eternity

- type: cargoProduct
  id: SecuritySwat
  icon:
    sprite: _DV/Clothing/OuterClothing/Armor/riot.rsi # DeltaV - resprite
    state: icon
  product: CrateSecuritySwat
  cost: 12500
  category: cargoproduct-category-name-security
  group: market
  excludedServers: [eternity] # DEN - Exclude dangerous prototypes from Eternity

- type: cargoProduct
  id: SecuritySupplies
  icon:
    sprite: Objects/Storage/boxes.rsi
    state: box_security
  product: CrateSecuritySupplies
  cost: 1000
  category: cargoproduct-category-name-security
  group: market
  excludedServers: [eternity] # DEN - Exclude dangerous prototypes from Eternity

- type: cargoProduct
  id: SecurityRestraints
  icon:
    sprite: Objects/Misc/handcuffs.rsi
    state: handcuff
  product: CrateRestraints
  cost: 1000
  category: cargoproduct-category-name-security
  group: market
  excludedServers: [eternity] # DEN - Exclude dangerous prototypes from Eternity

- type: cargoProduct
  id: SecurityBiosuit
  icon:
    sprite: Clothing/Head/Hoods/Bio/security.rsi
    state: icon
  product: CrateSecurityBiosuit
  cost: 800
  category: cargoproduct-category-name-security
  group: market
  excludedServers: [eternity] # DEN - Exclude dangerous prototypes from Eternity

- type: cargoProduct
  id: SecurityBarrier
  icon:
    sprite: Objects/Specific/Security/barrier.rsi
    state: idle
  product: DeployableBarrier
  cost: 1000
  category: cargoproduct-category-name-security
  group: market

- type: cargoProduct
  id: SecurityGenPopCloset
  icon:
    sprite: Structures/Storage/closet.rsi
    state: genpop
  product: LockerPrisoner
  cost: 250
  category: cargoproduct-category-name-security
  group: market
