# SPDX-FileCopyrightText: 2020 AJCM-git <60196617+AJCM-git@users.noreply.github.com>
# SPDX-FileCopyrightText: 2020 FL-OZ <58238103+FL-OZ@users.noreply.github.com>
# SPDX-FileCopyrightText: 2020 FL-OZ <anotherscuffed@gmail.com>
# SPDX-FileCopyrightText: 2020 Hugo Laloge <hugo.laloge@gmail.com>
# SPDX-FileCopyrightText: 2020 Peter Wedder <burneddi@gmail.com>
# SPDX-FileCopyrightText: 2020 ike709 <ike709@users.noreply.github.com>
# SPDX-FileCopyrightText: 2021 Elijahrane <60792108+Elijahrane@users.noreply.github.com>
# SPDX-FileCopyrightText: 2021 Mith-randalf <84274729+Mith-randalf@users.noreply.github.com>
# SPDX-FileCopyrightText: 2021 Paul Ritter <ritter.paul1@googlemail.com>
# SPDX-FileCopyrightText: 2021 ShadowCommander <10494922+ShadowCommander@users.noreply.github.com>
# SPDX-FileCopyrightText: 2021 Swept <sweptwastaken@protonmail.com>
# SPDX-FileCopyrightText: 2021 SweptWasTaken <sweptwastaken@protonmail.com>
# SPDX-FileCopyrightText: 2021 Vera Aguilera Puerto <6766154+Zumorica@users.noreply.github.com>
# SPDX-FileCopyrightText: 2021 metalgearsloth <31366439+metalgearsloth@users.noreply.github.com>
# SPDX-FileCopyrightText: 2022 Kara <lunarautomaton6@gmail.com>
# SPDX-FileCopyrightText: 2022 Lamrr <96937466+Lamrr@users.noreply.github.com>
# SPDX-FileCopyrightText: 2022 Leon Friedrich <60421075+ElectroJr@users.noreply.github.com>
# SPDX-FileCopyrightText: 2022 Moony <moonheart08@users.noreply.github.com>
# SPDX-FileCopyrightText: 2022 Morber <14136326+Morb0@users.noreply.github.com>
# SPDX-FileCopyrightText: 2022 Peptide90 <78795277+Peptide90@users.noreply.github.com>
# SPDX-FileCopyrightText: 2022 Pieter-Jan Briers <pieterjan.briers+git@gmail.com>
# SPDX-FileCopyrightText: 2022 Sissel <axel.roche@pm.me>
# SPDX-FileCopyrightText: 2022 Veritius <veritiusgaming@gmail.com>
# SPDX-FileCopyrightText: 2022 mirrorcult <lunarautomaton6@gmail.com>
# SPDX-FileCopyrightText: 2023 Chief-Engineer <119664036+Chief-Engineer@users.noreply.github.com>
# SPDX-FileCopyrightText: 2023 Colin-Tel <113523727+Colin-Tel@users.noreply.github.com>
# SPDX-FileCopyrightText: 2023 Debug <49997488+DebugOk@users.noreply.github.com>
# SPDX-FileCopyrightText: 2023 DrSmugleaf <DrSmugleaf@users.noreply.github.com>
# SPDX-FileCopyrightText: 2023 Emisse <99158783+Emisse@users.noreply.github.com>
# SPDX-FileCopyrightText: 2023 Fluffiest Floofers <thebluewulf@gmail.com>
# SPDX-FileCopyrightText: 2023 Nairod <110078045+Nairodian@users.noreply.github.com>
# SPDX-FileCopyrightText: 2023 PHCodes <47927305+PHCodes@users.noreply.github.com>
# SPDX-FileCopyrightText: 2023 PrPleGoo <PrPleGoo@users.noreply.github.com>
# SPDX-FileCopyrightText: 2023 coolmankid12345 <55817627+coolmankid12345@users.noreply.github.com>
# SPDX-FileCopyrightText: 2023 coolmankid12345 <coolmankid12345@users.noreply.github.com>
# SPDX-FileCopyrightText: 2023 keronshb <54602815+keronshb@users.noreply.github.com>
# SPDX-FileCopyrightText: 2023 potato1234_x <79580518+potato1234x@users.noreply.github.com>
# SPDX-FileCopyrightText: 2024 DEATHB4DEFEAT <77995199+DEATHB4DEFEAT@users.noreply.github.com>
# SPDX-FileCopyrightText: 2024 Fansana <116083121+Fansana@users.noreply.github.com>
# SPDX-FileCopyrightText: 2024 Fansana <fansana95@googlemail.com>
# SPDX-FileCopyrightText: 2024 FoxxoTrystan <trystan.garnierhein@gmail.com>
# SPDX-FileCopyrightText: 2024 flyingkarii <123355664+flyingkarii@users.noreply.github.com>
# SPDX-FileCopyrightText: 2024 flyingkarii <flyingkarii@gmail.com>
# SPDX-FileCopyrightText: 2024 sleepyyapril <flyingkarii@gmail.com>
# SPDX-FileCopyrightText: 2025 SixplyDev <einlichen@gmail.com>
# SPDX-FileCopyrightText: 2025 Skubman <ba.fallaria@gmail.com>
# SPDX-FileCopyrightText: 2025 Timfa <timfalken@hotmail.com>
# SPDX-FileCopyrightText: 2025 VMSolidus <evilexecutive@gmail.com>
# SPDX-FileCopyrightText: 2025 sleepyyapril <123355664+sleepyyapril@users.noreply.github.com>
#
# SPDX-License-Identifier: AGPL-3.0-or-later AND MIT

- type: job
  id: Captain
  name: job-name-captain
  description: job-description-captain
  playTimeTracker: JobCaptain
  requirements:
    - !type:CharacterPlaytimeRequirement
      tracker: JobQuartermaster # DeltaV - Logistics Department replacing Cargo
      min: 7200 # The Den - 2 hour
    - !type:CharacterPlaytimeRequirement
      tracker: JobChiefEngineer
      min: 7200 # The Den - 2 hour
    - !type:CharacterPlaytimeRequirement
      tracker: JobChiefMedicalOfficer
      min: 7200 # The Den - 2 hour
    - !type:CharacterPlaytimeRequirement
      tracker: JobHeadOfSecurity
      min: 7200 # The Den - 2 hour
    - !type:CharacterPlaytimeRequirement # DeltaV - Epistemics dept time requirement
      tracker: JobResearchDirector # DeltaV - Epistemics Department replacing Science
      min: 7200 # The Den - 2 hour
    - !type:CharacterPlaytimeRequirement # DeltaV - Epistemics dept time requirement
      tracker: JobHeadOfPersonnel # DeltaV - Epistemics Department replacing Science
      min: 7200 # The Den - 2 hour
    - !type:CharacterOverallTimeRequirement
      min: 144000 # The Den - 40 hour
  weight: 20
  startingGear: CaptainGear
  icon: "JobIconCaptain"
  requireAdminNotify: true
  joinNotifyCrew: true
  supervisors: job-supervisors-centcom
  canBeAntag: false
  accessGroups:
  - AllAccess
  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant ]
  - !type:AddComponentSpecial
    components:
      - type: CommandStaff
  afterLoadoutSpecial:
  - !type:ModifyEnvirosuitSpecial
    charges: 8
  - !type:ModifyEnvirohelmSpecial
    powerCell: PowerCellMedium

- type: startingGear
  id: CaptainGear
  subGear:
  - CaptainPlasmamanGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitCaptain
    back: ClothingBackpackCaptainFilled
    shoes: ClothingShoesBootsLaceup
    id: CaptainPDA
    ears: ClothingHeadsetAltCommand
  innerClothingSkirt: ClothingUniformJumpskirtCaptain
  satchel: ClothingBackpackSatchelCaptainFilled
  duffelbag: ClothingBackpackDuffelCaptainFilled

- type: startingGear
  id: CaptainPlasmamanGear
  parent: BasePlasmamanGear
  equipment:
    jumpsuit: ClothingUniformEnvirosuitCaptain
    head: ClothingHeadEnvirohelmCaptain
    gloves: ClothingHandsGlovesCaptain
