# SPDX-FileCopyrightText: 2020 20kdc <asdd2808@gmail.com>
# SPDX-FileCopyrightText: 2020 AJCM-git <60196617+AJCM-git@users.noreply.github.com>
# SPDX-FileCopyrightText: 2020 FL-OZ <58238103+FL-OZ@users.noreply.github.com>
# SPDX-FileCopyrightText: 2020 FL-OZ <anotherscuffed@gmail.com>
# SPDX-FileCopyrightText: 2020 Hugo Laloge <hugo.laloge@gmail.com>
# SPDX-FileCopyrightText: 2020 ike709 <ike709@users.noreply.github.com>
# SPDX-FileCopyrightText: 2021 Elijahrane <60792108+Elijahrane@users.noreply.github.com>
# SPDX-FileCopyrightText: 2021 Paul Ritter <ritter.paul1@googlemail.com>
# SPDX-FileCopyrightText: 2021 Swept <sweptwastaken@protonmail.com>
# SPDX-FileCopyrightText: 2021 Vera Aguilera Puerto <6766154+Zumorica@users.noreply.github.com>
# SPDX-FileCopyrightText: 2022 Kara <lunarautomaton6@gmail.com>
# SPDX-FileCopyrightText: 2022 Lamrr <96937466+Lamrr@users.noreply.github.com>
# SPDX-FileCopyrightText: 2022 Moony <moonheart08@users.noreply.github.com>
# SPDX-FileCopyrightText: 2022 Morber <14136326+Morb0@users.noreply.github.com>
# SPDX-FileCopyrightText: 2022 Nairod <110078045+Nairodian@users.noreply.github.com>
# SPDX-FileCopyrightText: 2022 Peptide90 <78795277+Peptide90@users.noreply.github.com>
# SPDX-FileCopyrightText: 2022 Pieter-Jan Briers <pieterjan.briers+git@gmail.com>
# SPDX-FileCopyrightText: 2022 Sissel <axel.roche@pm.me>
# SPDX-FileCopyrightText: 2022 Veritius <veritiusgaming@gmail.com>
# SPDX-FileCopyrightText: 2023 Adrian16199 <144424013+Adrian16199@users.noreply.github.com>
# SPDX-FileCopyrightText: 2023 Chief-Engineer <119664036+Chief-Engineer@users.noreply.github.com>
# SPDX-FileCopyrightText: 2023 Colin-Tel <113523727+Colin-Tel@users.noreply.github.com>
# SPDX-FileCopyrightText: 2023 DrSmugleaf <DrSmugleaf@users.noreply.github.com>
# SPDX-FileCopyrightText: 2023 Emisse <99158783+Emisse@users.noreply.github.com>
# SPDX-FileCopyrightText: 2023 Fluffiest Floofers <thebluewulf@gmail.com>
# SPDX-FileCopyrightText: 2023 Moony <moony@hellomouse.net>
# SPDX-FileCopyrightText: 2023 PHCodes <47927305+PHCodes@users.noreply.github.com>
# SPDX-FileCopyrightText: 2023 PrPleGoo <PrPleGoo@users.noreply.github.com>
# SPDX-FileCopyrightText: 2023 Tad "Taddy" Johnson <120885811+TadJohnson00@users.noreply.github.com>
# SPDX-FileCopyrightText: 2023 Ubaser <134914314+UbaserB@users.noreply.github.com>
# SPDX-FileCopyrightText: 2023 Vasilis <vasilis@pikachu.systems>
# SPDX-FileCopyrightText: 2023 Velcroboy <107660393+IamVelcroboy@users.noreply.github.com>
# SPDX-FileCopyrightText: 2023 Vordenburg <114301317+Vordenburg@users.noreply.github.com>
# SPDX-FileCopyrightText: 2023 coolmankid12345 <55817627+coolmankid12345@users.noreply.github.com>
# SPDX-FileCopyrightText: 2023 coolmankid12345 <coolmankid12345@users.noreply.github.com>
# SPDX-FileCopyrightText: 2023 lzk228 <124214523+lzk228@users.noreply.github.com>
# SPDX-FileCopyrightText: 2023 moonheart08 <moonheart08@users.noreply.github.com>
# SPDX-FileCopyrightText: 2023 nmajask <nmajask@gmail.com>
# SPDX-FileCopyrightText: 2023 randy10122 <88034663+randy10122@users.noreply.github.com>
# SPDX-FileCopyrightText: 2024 DEATHB4DEFEAT <77995199+DEATHB4DEFEAT@users.noreply.github.com>
# SPDX-FileCopyrightText: 2024 Debug <49997488+DebugOk@users.noreply.github.com>
# SPDX-FileCopyrightText: 2024 Fansana <116083121+Fansana@users.noreply.github.com>
# SPDX-FileCopyrightText: 2024 Fansana <fansana95@googlemail.com>
# SPDX-FileCopyrightText: 2024 FoxxoTrystan <trystan.garnierhein@gmail.com>
# SPDX-FileCopyrightText: 2024 Nairod <110078045+nairodian@users.noreply.github.com>
# SPDX-FileCopyrightText: 2024 flyingkarii <123355664+flyingkarii@users.noreply.github.com>
# SPDX-FileCopyrightText: 2024 flyingkarii <flyingkarii@gmail.com>
# SPDX-FileCopyrightText: 2025 SixplyDev <einlichen@gmail.com>
# SPDX-FileCopyrightText: 2025 Skubman <ba.fallaria@gmail.com>
# SPDX-FileCopyrightText: 2025 Timfa <timfalken@hotmail.com>
# SPDX-FileCopyrightText: 2025 VMSolidus <evilexecutive@gmail.com>
# SPDX-FileCopyrightText: 2025 sleepyyapril <123355664+sleepyyapril@users.noreply.github.com>
#
# SPDX-License-Identifier: AGPL-3.0-or-later AND MIT

- type: job
  id: HeadOfPersonnel
  name: job-name-hop
  description: job-description-hop
  playTimeTracker: JobHeadOfPersonnel
  requirements:
    - !type:CharacterDepartmentTimeRequirement # DeltaV - Civilian dept time requirement
      department: Civilian
      min: 28800 # The Den - 8 hours
    - !type:CharacterPlaytimeRequirement
      tracker: JobChef
      min: 7200 # The Den - 2 hour
    - !type:CharacterPlaytimeRequirement
      tracker: JobBotanist
      min: 7200 # The Den - 2 hour
  weight: 10 # DeltaV - Changed HoP weight from 20 to 10 due to them not being more important than other Heads
  startingGear: HoPGear
  icon: "JobIconHeadOfPersonnel"
  requireAdminNotify: true
  supervisors: job-supervisors-captain
  canBeAntag: false
  access:
  - Command
  - HeadOfPersonnel
  - Bar
  - Service
  - Maintenance
  - Janitor
  - Theatre
  - Kitchen
#  - Chapel
  - Hydroponics
  - External
  - Cryogenics
  # I mean they'll give themselves the rest of the access levels *anyways*.
  # As of 15/03/23 they can't do that so here's MOST of the rest of the access levels.
  # Head level access that isn't their own was deliberately left out, get AA from the captain instead.
  # Delta V - fuck all of this HoP is a service role
#  - Chemistry
#  - Engineering
#  - Research
#  - Detective
#  - Salvage
#  - Security # NoooOoOo!! My HoPcurity!1
#  - Brig
  - Lawyer
  - Cargo
#  - Atmospherics
#  - Medical
  - Boxer # DeltaV - Add Boxer access
  - Clown # DeltaV - Add Clown access
  - Library # DeltaV - Add Library access
  - Mime # DeltaV - Add Mime access
  - Musician # DeltaV - Add Musician access
  - Reporter # DeltaV - Add Reporter access
  - Zookeeper # DeltaV - Add Zookeeper access
  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant ]
  - !type:AddComponentSpecial
    components:
      - type: CommandStaff
  afterLoadoutSpecial:
  - !type:ModifyEnvirosuitSpecial
    charges: 8
  - !type:ModifyEnvirohelmSpecial
    powerCell: PowerCellMedium

- type: startingGear
  id: HoPGear
  subGear:
  - HoPPlasmamanGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitHoP
    back: ClothingBackpackHOPFilled
    shoes: ClothingShoesLeather # DeltaV - HoP needs something better than plebe shoes.
    id: HoPPDA
    ears: ClothingHeadsetHoP # DeltaV - HoP is now a service role, replaces their all channels headset.
  innerClothingSkirt: ClothingUniformJumpskirtHoP
  satchel: ClothingBackpackSatchelHOPFilled
  duffelbag: ClothingBackpackDuffelHOPFilled

- type: startingGear
  id: HoPPlasmamanGear
  parent: BasePlasmamanGear
  equipment:
    jumpsuit: ClothingUniformEnvirosuitHoP
    head: ClothingHeadEnvirohelmHoP
    gloves: ClothingHandsGlovesEnviroglovesHoP
