# SPDX-FileCopyrightText: 2025 William Lemon
# SPDX-FileCopyrightText: 2025 eightballll
#
# SPDX-License-Identifier: AGPL-3.0-or-later

- type: antag
  id: Skia
  name: roles-antag-skia-name
  objective: roles-antag-skia-objective
  antagonist: true