# SPDX-FileCopyrightText: 2022 DrSmugleaf
# SPDX-FileCopyrightText: 2022 EmoGarbage404
# SPDX-FileCopyrightText: 2022 Kara
# SPDX-FileCopyrightText: 2022 Morber
# SPDX-FileCopyrightText: 2022 Paul Ritter
# SPDX-FileCopyrightText: 2022 Peptide90
# SPDX-FileCopyrightText: 2022 Pieter-Jan Briers
# SPDX-FileCopyrightText: 2022 Sissel
# SPDX-FileCopyrightText: 2022 Veritius
# SPDX-FileCopyrightText: 2023 Debug
# SPDX-FileCopyrightText: 2023 Flareguy
# SPDX-FileCopyrightText: 2023 JoeHammad1844
# SPDX-FileCopyrightText: 2023 Kit0vras
# SPDX-FileCopyrightText: 2023 Nairod
# SPDX-FileCopyrightText: 2023 Nim
# SPDX-FileCopyrightText: 2023 PrPleGoo
# SPDX-FileCopyrightText: 2023 Whisper
# SPDX-FileCopyrightText: 2024 Hanz
# SPDX-FileCopyrightText: 2024 IProduceWidgets
# SPDX-FileCopyrightText: 2024 VMSolidus
# SPDX-FileCopyrightText: 2025 Jakumba
# SPDX-FileCopyrightText: 2025 RosySaturniidae
# SPDX-FileCopyrightText: 2025 Skubman
# SPDX-FileCopyrightText: 2025 Vanessa
# SPDX-FileCopyrightText: 2025 sleepyyapril
#
# SPDX-License-Identifier: AGPL-3.0-or-later AND MIT


# Base
- type: startingGear
  id: BaseERTGear
  equipment:
    shoes: ClothingShoesBootsCombatFilled
    mask: ClothingMaskGasERT
    eyes: ClothingEyesHudERT
    gloves: ClothingHandsGlovesCombat
    outerClothing: ClothingOuterArmorBasicSlim
    ears: ClothingHeadsetAltCentCom
    belt: ClothingBeltERTWebbingFilled
    pocket1: WeaponDisabler

# Leader
- type: job
  id: ERTLeader
  name: job-name-ertleader
  description: job-description-ertleader
  playTimeTracker: JobERTLeader
  setPreference: false
  startingGear: ERTLeaderGear
  icon: "JobIconERTLeader"
  supervisors: job-supervisors-centcom
  canBeAntag: false
  special:
  - !type:AddImplantSpecial
    implants: [ CentCommImplant, BluespaceLifelineImplant ]
  accessGroups:
  - AllAccess
  access:
  - CentralCommand

- type: startingGear
  id: ERTLeaderGear
  parent: BaseERTGear
  equipment:
    head: ClothingHeadHelmetERTLeader
    jumpsuit: ClothingUniformJumpsuitERTLeader
    back: ClothingBackpackERTLeaderFilled
    id: ERTLeaderPDA
    belt: ClothingBeltERTLeaderWebbingFilled
    pocket1: WeaponTaser
    pocket2: ERTLeaderLoadoutSelector

# Chaplain
- type: job
  id: ERTChaplain
  name: job-name-ertchaplain
  description: job-description-ertchaplain
  playTimeTracker: JobERTChaplain
  setPreference: false
  startingGear: ERTChaplainGear
  icon: "JobIconERTChaplain"
  supervisors: job-supervisors-centcom
  canBeAntag: false
  accessGroups:
  - AllAccess
  access:
  - CentralCommand
  special:
  - !type:AddComponentSpecial
    components:
    - type: BibleUser #Lets them heal with bibles
  - !type:AddImplantSpecial
    implants: [ CentCommImplant, BluespaceLifelineImplant ]

- type: startingGear
  id: ERTChaplainGear
  parent: BaseERTGear
  equipment:
    head: ClothingHeadHatBeretRND
    jumpsuit: ClothingUniformJumpsuitERTChaplain
    back: ClothingBackpackERTChaplainFilled
    neck: ClothingNeckStoleChaplain
    id: ERTChaplainPDA

# Engineer
- type: job
  id: ERTEngineer
  name: job-name-ertengineer
  description: job-description-ertengineer
  playTimeTracker: JobERTEngineer
  setPreference: false
  startingGear: ERTEngineerGear
  icon: "JobIconERTEngineer"
  supervisors: job-supervisors-centcom
  canBeAntag: false
  special:
  - !type:AddImplantSpecial
    implants: [ CentCommImplant, BluespaceLifelineImplant ]
  accessGroups:
  - AllAccess
  access:
  - CentralCommand

- type: startingGear
  id: ERTEngineerGear
  parent: BaseERTGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitERTEngineer
    back: ClothingBackpackERTEngineerFilled
    head: ClothingHeadHelmetERTEngineer
    eyes: ClothingEyesHudERTEngineer
    id: ERTEngineerPDA
    pocket2: ERTEngineerLoadoutSelector

# Security
- type: job
  id: ERTSecurity
  name: job-name-ertsecurity
  description: job-description-ertsecurity
  playTimeTracker: JobERTSecurity
  setPreference: false
  startingGear: ERTSecurityGear
  icon: "JobIconERTSecurity"
  supervisors: job-supervisors-centcom
  canBeAntag: false
  special:
  - !type:AddImplantSpecial
    implants: [ CentCommImplant, BluespaceLifelineImplant ]
  accessGroups:
  - AllAccess
  access:
  - CentralCommand

- type: startingGear
  id: ERTSecurityGear
  parent: BaseERTGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitERTSecurity
    back: ClothingBackpackERTSecurityFilled
    head: ClothingHeadHelmetERTSecurity
    id: ERTSecurityPDA
    pocket1: WeaponTaser
    pocket2: ERTSecurityLoadoutSelector


# Medical
- type: job
  id: ERTMedical
  name: job-name-ertmedic
  description: job-description-ertmedic
  playTimeTracker: JobERTMedical
  setPreference: false
  startingGear: ERTMedicalGear
  icon: "JobIconERTMedic"
  supervisors: job-supervisors-centcom
  canBeAntag: false
  special:
  - !type:AddImplantSpecial
    implants: [ CentCommImplant, BluespaceLifelineImplant ]
  accessGroups:
  - AllAccess
  access:
  - CentralCommand

- type: startingGear
  id: ERTMedicalGear
  parent: BaseERTGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitERTMedic
    back: ClothingBackpackERTMedicalFilled
    head: ClothingHeadHelmetERTMedic
    eyes: ClothingEyesHudERTMedic
    gloves: ClothingHandsGlovesNitrile
    id: ERTMedicPDA
    pocket2: ERTMedicLoadoutSelector

# Janitor
- type: job
  id: ERTJanitor
  name: job-name-ertjanitor
  description: job-description-ertjanitor
  playTimeTracker: JobERTJanitor
  setPreference: false
  startingGear: ERTJanitorGear
  icon: "JobIconERTJanitor"
  supervisors: job-supervisors-centcom
  canBeAntag: false
  special:
  - !type:AddImplantSpecial
    implants: [ CentCommImplant, BluespaceLifelineImplant ]
  accessGroups:
  - AllAccess
  access:
  - CentralCommand

- type: startingGear
  id: ERTJanitorGear
  parent: BaseERTGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitERTJanitor
    back: ClothingBackpackERTJanitorFilled
    shoes: ClothingShoesGaloshes
    head: ClothingHeadHelmetERTJanitor
    id: ERTJanitorPDA
    pocket2: ERTJanitorLoadoutSelector
