# SPDX-FileCopyrightText: 2025 ASaltySeabass
# SPDX-FileCopyrightText: 2025 John Willis
# SPDX-FileCopyrightText: 2025 KekaniCreates
# SPDX-FileCopyrightText: 2025 MajorMoth
# SPDX-FileCopyrightText: 2025 Rosycup
# SPDX-FileCopyrightText: 2025 Rouge2t7
# SPDX-FileCopyrightText: 2025 SixplyDev
# SPDX-FileCopyrightText: 2025 Skubman
# SPDX-FileCopyrightText: 2025 Timfa
# SPDX-FileCopyrightText: 2025 Vanessa
# SPDX-FileCopyrightText: 2025 astriloqua
# SPDX-FileCopyrightText: 2025 sleepyyapril
#
# SPDX-License-Identifier: AGPL-3.0-or-later AND MIT

- type: job
  id: BlueshieldOfficer
  name: Blueshield Officer
  description: "Act as a bodyguard and advisor for Command and CentComm VIPs."
  playTimeTracker: JobBlueshieldOfficer
  requirements:
    - !type:CharacterDepartmentTimeRequirement
      department: Command
      min: 54000 # 15 hours
    - !type:CharacterDepartmentTimeRequirement
      department: Medical
      min: 54000 # 15 hours
    - !type:CharacterDepartmentTimeRequirement
      department: Security
      min: 54000 # 15 hours
  weight: 20
  startingGear: BlueshieldOfficerGear
  icon: "JobIconBlueshield"
  requireAdminNotify: true
  joinNotifyCrew: true
  whitelisted: true
  supervisors: job-supervisors-centcom
  canBeAntag: false
  accessGroups:
  - BasicAllAccess
  access:
  - BlueshieldOfficer
  - CentralCommand
  - Corpsman
  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant ]
  - !type:AddComponentSpecial
    components:
      - type: CommandStaff
      - type: CPRTraining
  afterLoadoutSpecial:
  - !type:ModifyEnvirosuitSpecial
    charges: 8
  - !type:ModifyEnvirohelmSpecial
    powerCell: PowerCellMedium

- type: startingGear
  id: BlueshieldOfficerGear
  subGear:
  - BlueshieldPlasmamanGear
  equipment:
    back: ClothingBackpackBlueshield
    jumpsuit: ClothingUniformJumpsuitBlueshieldOfficer
    shoes: ClothingShoesBootsCombatFilled
    eyes: ClothingEyesGlassesMedSec
    ears: ClothingHeadsetAltCentCom
    belt: ClothingBeltBSOWebbingFilled #TheDen
    gloves: ClothingHandsGlovesCombat
    id: BlueshieldPDA
    pocket1: UniqueBlueshieldOfficerLockerTeleporter
    pocket2: BluespaceLifelineImplanter

    #outerClothing: ClothingBlueshieldArmourVest
    #ears: ClothingHeadsetAltCommand
    #belt: ClothingBeltSecurityFilled
    #pocket1: WeaponPistolMk58
    #pocket2: DeathAcidifierImplanter

- type: startingGear
  id: BlueshieldPlasmamanGear
  parent: BasePlasmamanGear
  equipment:
    jumpsuit: ClothingUniformEnvirosuitBlueshield
    head: ClothingHeadEnvirohelmBlueshield
    gloves: ClothingHandsGlovesEnviroglovesBlack
