# SPDX-FileCopyrightText: 2025 John Willis <143434770+CerberusWolfie@users.noreply.github.com>
# SPDX-FileCopyrightText: 2025 SixplyDev <einlichen@gmail.com>
# SPDX-FileCopyrightText: 2025 Skubman <ba.fallaria@gmail.com>
# SPDX-FileCopyrightText: 2025 Timfa <timfalken@hotmail.com>
# SPDX-FileCopyrightText: 2025 sleepyyapril <123355664+sleepyyapril@users.noreply.github.com>
#
# SPDX-License-Identifier: AGPL-3.0-or-later AND MIT

- type: job
  id: Magistrate
  name: Magistrate
  description: "Ensure Space Law is being followed, Uphold Justice and Legality, Hold Hearings and Trials, Follow SOP, Ensure Command is Following Space Law."
  playTimeTracker: JobMagistrate
  requirements:
    - !type:CharacterDepartmentTimeRequirement
      department: Command
      min: 54000 # 15 hours
    - !type:CharacterDepartmentTimeRequirement
      department: Security
      min: 54000 # 15 hours
  weight: 20
  startingGear: MagistrateGear
  icon: "JobIconMagistrate"
  requireAdminNotify: true
  joinNotifyCrew: true
  supervisors: job-supervisors-centcom
  canBeAntag: false
  accessGroups:
  - BasicAllAccess
  access:
  - CentralCommand
  - Magistrate
  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant ]
  - !type:AddComponentSpecial
    components:
      - type: CommandStaff
  afterLoadoutSpecial:
  - !type:ModifyEnvirosuitSpecial
    charges: 8
  - !type:ModifyEnvirohelmSpecial
    powerCell: PowerCellMedium

- type: startingGear
  id: MagistrateGear
  subGear:
  - MagistratePlasmamanGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitMagistrate
    shoes: ClothingShoesLeather
    gloves: ClothingHandsGlovesColorWhite
    id: CentcomPDA
    ears: ClothingHeadsetMagistrate
    pocket1: UniqueMagistrateLockerTeleporter

- type: startingGear
  id: MagistratePlasmamanGear
  parent: BasePlasmamanGear
  equipment:
    jumpsuit: ClothingUniformEnvirosuitMagistrate
    head: ClothingHeadEnvirohelmMagistrate
    gloves: ClothingHandsGlovesEnviroglovesWhite
