- type: entity
  parent: BaseMindRoleAntag
  id: MindRoleSkia
  name: Skia Role
  components:
  - type: MindRole
    roleType: SoloAntagonist
    antagPrototype: Skia
    exclusiveAntag: true
  - type: SkiaRole
  - type: RoleBriefing
    briefing: skia-role-briefing
