# SPDX-FileCopyrightText: 2024 sleepyyapril <flyingkarii@gmail.com>
# SPDX-FileCopyrightText: 2025 sleepyyapril <123355664+sleepyyapril@users.noreply.github.com>
#
# SPDX-License-Identifier: AGPL-3.0-or-later AND MIT

- type: job
  id: CBURN
  name: job-name-cburn
  description: job-description-cburn
  playTimeTracker: JobCBURN
  setPreference: false
  startingGear: CBURNGear
  icon: "JobIconCBURN"
  supervisors: job-supervisors-centcom
  canBeAntag: false
  special:
  - !type:AddImplantSpecial
    implants: [ CentCommImplant ]
  accessGroups:
  - AllAccess
  access:
  - CentralCommand
