# SPDX-FileCopyrightText: 2023 Bakke
# SPDX-FileCopyrightText: 2023 Colin-Tel
# SPDX-FileCopyrightText: 2023 Fluffiest Floofers
# SPDX-FileCopyrightText: 2024 BonkTrauma
# SPDX-FileCopyrightText: 2024 DEATHB4DEFEAT
# SPDX-FileCopyrightText: 2024 Debug
# SPDX-FileCopyrightText: 2024 Fansana
# SPDX-FileCopyrightText: 2024 FoxxoTrystan
# SPDX-FileCopyrightText: 2024 VMSolidus
# SPDX-FileCopyrightText: 2025 Blitz
# SPDX-FileCopyrightText: 2025 DoctorJado
# SPDX-FileCopyrightText: 2025 Rosycup
# SPDX-FileCopyrightText: 2025 SixplyDev
# SPDX-FileCopyrightText: 2025 Skubman
# SPDX-FileCopyrightText: 2025 sleepyyapril
#
# SPDX-License-Identifier: MIT AND AGPL-3.0-or-later

- type: job
  id: Prisoner
  name: job-name-prisoner
  description: job-description-prisoner
  playTimeTracker: JobPrisoner
  startingGear: PrisonerGear
  alwaysUseSpawner: true
  canBeAntag: false
  icon: "JobIconPrisoner"
  supervisors: job-supervisors-security
  requirements:
    - !type:CharacterDepartmentTimeRequirement
      department: Security
      min: 21600
  afterLoadoutSpecial:
  - !type:ModifyEnvirosuitSpecial
    charges: 3 # Poor prisoners with not a lot of self-extinguishes.
  - !type:ModifyEnvirohelmSpecial
    powerCell: PowerCellPotato
  adjustableCount: true

- type: startingGear
  id: PrisonerGear
  subGear:
  - PrisonerPlasmamanGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitPrisoner
    shoes: ClothingShoesColorBlack
    id: PrisonerPDA
    ears: ClothingHeadsetPrison #deltaV
  innerClothingSkirt: ClothingUniformJumpsuitPrisoner

- type: startingGear
  id: PrisonerPlasmamanGear
  parent: BasePlasmamanGear
  equipment:
    jumpsuit: ClothingUniformEnvirosuitPrisoner
    head: ClothingHeadEnvirohelmPrisoner
    gloves: ClothingHandsGlovesEnviroglovesBlack
