# SPDX-FileCopyrightText: 2025 Dirius77
# SPDX-FileCopyrightText: 2025 sleepyyapril
#
# SPDX-License-Identifier: AGPL-3.0-or-later

- type: alternateJobTitle
  id: DefaultCaptain
  jobId: Captain
  titles:
  - job-name-alternate-commander
  - job-name-alternate-shogun

- type: alternateJobTitle
  id: DefaultAdminAssistant
  jobId: AdministrativeAssistant
  titles:
  - job-name-alternate-unpaid-intern
  - job-name-alternate-secretary
