# SPDX-FileCopyrightText: 2025 ASaltySeabass
# SPDX-FileCopyrightText: 2025 Jakumba
# SPDX-FileCopyrightText: 2025 sleepyyapril
#
# SPDX-License-Identifier: MIT

- type: alternateJobTitle
  id: DefaultScientist
  jobId: Scientist
  titles:
  - job-name-alternate-lab-tech
  - job-name-alternate-xenoarch
  - job-name-alternate-researcher
  - job-name-alternate-acolyte

- type: alternateJobTitle
  id: DefaultRoboticist
  jobId: Roboticist
  titles:
  - job-name-alternate-positronic-technician
  - job-name-alternate-mech-technician
  - job-name-alternate-cyborg-specialist
  - job-name-alternate-bionic-engineer
  - job-name-alternate-biomechanical-engineer
  - job-name-alternate-ripperdoc
  - job-name-alternate-cybernetics-specialist

- type: alternateJobTitle
  id: DefaultResearchDirector
  jobId: ResearchDirector
  titles:
    - job-name-alternate-chief-scientist
    - job-name-alternate-head-researcher
    - job-name-alternate-research-coordinator
    - job-name-alternate-research-director

- type: alternateJobTitle
  id: DefaultChaplain
  jobId: Chaplain
  titles:
    - job-name-alternate-cleric
    - job-name-alternate-priest
    - job-name-alternate-priestess
    - job-name-alternate-curate
    - job-name-alternate-officiant
    - job-name-alternate-reverend
    - job-name-alternate-shaman

- type: alternateJobTitle
  id: DefaultSeniorResearcher
  jobId: SeniorResearcher
  titles:
    - job-name-alternate-mystic
    - job-name-alternate-sage
    - job-name-alternate-seer
    - job-name-alternate-senior-research-fellow

- type: alternateJobTitle
  id: DefaultLibrarian
  jobId: Librarian
  titles:
    - job-name-alternate-librarian
    - job-name-alternate-scholar
    - job-name-alternate-archivist
    - job-name-alternate-professor
    - job-name-alternate-loremaster
    - job-name-alternate-dungeon-master

- type: alternateJobTitle
  id: DefaultResearchAssistant
  jobId: ResearchAssistant
  titles:
  - job-name-alternate-lab-assistant
  - job-name-alternate-initiate
  - job-name-alternate-novitiate
  - job-name-alternate-research-associate
