# SPDX-FileCopyrightText: 2025 ASaltySeabass
# SPDX-FileCopyrightText: 2025 Jakumba
# SPDX-FileCopyrightText: 2025 XenoOutlier
# SPDX-FileCopyrightText: 2025 sleepyyapril
#
# SPDX-License-Identifier: MIT

- type: alternateJobTitle
  id: DefaultHeadOfSecurity
  jobId: HeadOfSecurity
  titles:
  - job-name-alternate-sheriff
  - job-name-alternate-security-director
  - job-name-alternate-security-chief
  - job-name-alternate-daimyo
  - job-name-alternate-chief-constable

- type: alternateJobTitle
  id: DefaultSecurityOfficer
  jobId: SecurityOfficer
  titles:
  - job-name-alternate-deputy
  - job-name-alternate-peacekeeper
  - job-name-alternate-security-guard
  - job-name-alternate-nt-trooper
  - job-name-alternate-constable

- type: alternateJobTitle
  id: DefaultSeniorOfficer
  jobId: SeniorOfficer
  titles:
  - job-name-alternate-ranger
  - job-name-alternate-senior-guard
  - job-name-alternate-senior-trooper
  - job-name-alternate-sergeant

- type: alternateJobTitle
  id: DefaultCorpsman
  jobId: Brigmedic
  titles:
  - job-name-alternate-brigmedic
  - job-name-alternate-field-medic
  - job-name-alternate-combat-medic

- type: alternateJobTitle
  id: DefaultDetective
  jobId: Detective
  titles:
  - job-name-alternate-inspector
  - job-name-alternate-investigator
  - job-name-alternate-gumshoe
  - job-name-alternate-forensic-scientist

- type: alternateJobTitle
  id: DefaultWarden
  jobId: Warden
  titles:
  - job-name-alternate-armorer
  - job-name-alternate-armourer
  - job-name-alternate-deputy-head
  - job-name-alternate-deputy-chief
  - job-name-alternate-assistant-security-director
  - job-name-alternate-deputy-security-director
  - job-name-alternate-bailiff
  - job-name-alternate-marshal
  - job-name-alternate-deputy-chief-constable

- type: alternateJobTitle
  id: DefaultSecurityCadet
  jobId: SecurityCadet
  titles:
  - job-name-alternate-junior-officer
  - job-name-alternate-security-trainee

- type: alternateJobTitle
  id: DefaultPrisonGuard
  jobId: PrisonGuard
  titles:
  - job-name-alternate-officer-support-grade
  - job-name-alternate-detention-officer
  - job-name-alternate-corrections-officer
  - job-name-alternate-enforcement-officer
