# SPDX-FileCopyrightText: 2025 ASaltySeabass
# SPDX-FileCopyrightText: 2025 Jakumba
# SPDX-FileCopyrightText: 2025 Winter
# SPDX-FileCopyrightText: 2025 XenoOutlier
# SPDX-FileCopyrightText: 2025 sleepyyapril
#
# SPDX-License-Identifier: MIT

- type: alternateJobTitle
  id: DefaultPassenger
  jobId: Passenger
  titles:
  - job-name-alternate-assistant
  - job-name-alternate-tourist
  - job-name-alternate-off-duty
  - job-name-alternate-fisher
  - job-name-alternate-fish-enthusiast
  - job-name-alternate-angler

- type: alternateJobTitle
  id: DefaultBartender
  jobId: Bartender
  titles:
  - job-name-alternate-mixologist
  - job-name-alternate-barista
  - job-name-alternate-waiter
  - job-name-alternate-tapster
  - job-name-alternate-alcoholic-technician
  - job-name-alternate-barmaid
  - job-name-alternate-tavern-keeper

- type: alternateJobTitle
  id: DefaultBotanist
  jobId: Botanist
  titles:
  - job-name-alternate-farmer
  - job-name-alternate-gardener
  - job-name-alternate-hydroponics-technician
  - job-name-alternate-herbalist

- type: alternateJobTitle
  id: DefaultChef
  jobId: Chef
  titles:
  - job-name-alternate-baker
  - job-name-alternate-butcher
  - job-name-alternate-cuisinic-technician
  - job-name-alternate-culinarian
  - job-name-alternate-chef-de-cuisine
  - job-name-alternate-patissier
  - job-name-alternate-cook
  - job-name-alternate-mess-officer

- type: alternateJobTitle
  id: DefaultClown
  jobId: Clown
  titles:
  - job-name-alternate-jester
  - job-name-alternate-fool
  - job-name-alternate-harlequin
  - job-name-alternate-entertainer
  - job-name-alternate-pierrot

- type: alternateJobTitle
  id: DefaultMusician
  jobId: Musician
  titles:
  - job-name-alternate-dj
  - job-name-alternate-performer
  - job-name-alternate-singer
  - job-name-alternate-composer
  - job-name-alternate-guitarist
  - job-name-alternate-pianist
  - job-name-alternate-drummer
  - job-name-alternate-busker

- type: alternateJobTitle
  id: DefaultGladiator
  jobId: Gladiator
  titles:
  - job-name-alternate-combatant
  - job-name-alternate-performance-fighter

- type: alternateJobTitle
  id: DefaultPrisoner
  jobId: Prisoner
  titles:
  - job-name-alternate-Inmate
  - job-name-alternate-Convict
  - job-name-alternate-minimum-security-prisoner
  - job-name-alternate-medium-security-prisoner
  - job-name-alternate-maximum-security-prisoner

- type: alternateJobTitle
  id: DefaultMime
  jobId: Mime
  titles:
  - job-name-alternate-mummer
  - job-name-alternate-interpretive-dancer
  - job-name-alternate-mute

- type: alternateJobTitle
  id: DefaultHeadOfPersonnel
  jobId: HeadOfPersonnel
  titles:
  - job-name-alternate-bureaucratic-ambassador
  - job-name-alternate-paperwork-enthusiast
  - job-name-alternate-recruiter
  - job-name-alternate-head-of-service
  - job-name-alternate-service-director

- type: alternateJobTitle
  id: DefaultReporter
  jobId: Reporter
  titles:
    - job-name-alternate-journalist
    - job-name-alternate-correspondent
    - job-name-alternate-radio-host
    - job-name-alternate-investigative-journalist
    - job-name-alternate-paparazzo

- type: alternateJobTitle
  id: DefaultJanitor
  jobId: Janitor
  titles:
    - job-name-alternate-hygiene-technician
    - job-name-alternate-custodian
    - job-name-alternate-maid
    - job-name-alternate-butler

- type: alternateJobTitle
  id: DefaultServiceWorker
  jobId: ServiceWorker
  titles:
    - job-name-alternate-assistant-chef
    - job-name-alternate-assistant-bartender
    - job-name-alternate-assistant-botanist

- type: alternateJobTitle
  id: DefaultBoxer
  jobId: Boxer
  titles:
    - job-name-alternate-physical-trainer
    - job-name-alternate-wrestler
    - job-name-alternate-luchador
    - job-name-alternate-heel
    - job-name-alternate-pugilist
    - job-name-alternate-prize-fighter

- type: alternateJobTitle
  id: DefaultMartialArtist
  jobId: MartialArtist
  titles:
    - job-name-alternate-black-belt
    - job-name-alternate-mma-fighter
    - job-name-alternate-sensei
    - job-name-alternate-shifu
    - job-name-alternate-warrior-monk
