# SPDX-FileCopyrightText: 2023 Colin-Tel
# SPDX-FileCopyrightText: 2023 Fluffiest Floofers
# SPDX-FileCopyrightText: 2023 Tad "Taddy" Johnson
# SPDX-FileCopyrightText: 2023 Velcroboy
# SPDX-FileCopyrightText: 2024 DEATHB4DEFEAT
# SPDX-FileCopyrightText: 2024 FoxxoTrystan
# SPDX-FileCopyrightText: 2024 SimpleStation14
# SPDX-FileCopyrightText: 2024 Tmanzxd
# SPDX-FileCopyrightText: 2024 VMSolidus
# SPDX-FileCopyrightText: 2024 gluesniffler
# SPDX-FileCopyrightText: 2025 Adrian16199
# SPDX-FileCopyrightText: 2025 MajorMoth
# SPDX-FileCopyrightText: 2025 Rosycup
# SPDX-FileCopyrightText: 2025 Sir Warock
# SPDX-FileCopyrightText: 2025 SixplyDev
# SPDX-FileCopyrightText: 2025 Skubman
# SPDX-FileCopyrightText: 2025 Timfa
# SPDX-FileCopyrightText: 2025 sleepyyapril
#
# SPDX-License-Identifier: AGPL-3.0-or-later AND MIT

- type: job
  id: Brigmedic
  name: job-name-brigmedic
  description: job-description-brigmedic
  playTimeTracker: JobBrigmedic
  requirements:
    - !type:CharacterDepartmentTimeRequirement
      department: Medical
      min: 21600 # 6 hrs
    - !type:CharacterDepartmentTimeRequirement
      department: Security
      min: 18000 # 4 hrs
  startingGear: CorpsmanGear
  icon: "JobIconBrigmedic"
  supervisors: job-supervisors-hos
  canBeAntag: false
  access:
  - Medical
  - Security
  #- Brig #Delta V: Removed brig access
  - Maintenance
  - External
  - Corpsman
  extendedAccess:
  - Chemistry
  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant ]
  - !type:AddComponentSpecial
    components:
    - type: CPRTraining
  afterLoadoutSpecial:
  - !type:ModifyEnvirosuitSpecial
    charges: 6
  - !type:ModifyEnvirohelmSpecial
    powerCell: PowerCellMedium

- type: startingGear
  id: CorpsmanGear # see Prototypes/Roles/Jobs/Fun/misc_startinggear.yml for "BrigmedicGear"
  subGear:
  - CorpsmanPlasmamanGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitBrigmedic
#   outerClothing: ClothingOuterArmorPlateCarrier # Makin it be an option in loadouts
    back: ClothingBackpackBrigmedic
    shoes: ClothingShoesBootsCombatFilled
    gloves: ClothingHandsGlovesNitrile
    eyes: ClothingEyesHudMedical
    head: ClothingHeadHatBeretCorpsman
    id: CorpsmanPDA
    ears: ClothingHeadsetBrigmedic
    belt: ClothingBeltCorpsmanWebbingFilled
  innerClothingSkirt: ClothingUniformJumpskirtBrigmedic
  satchel: ClothingBackpackSatchelBrigmedic
  duffelbag: ClothingBackpackDuffelBrigmedic

- type: startingGear
  id: CorpsmanPlasmamanGear
  parent: BasePlasmamanSecurityGear
  equipment:
    jumpsuit: ClothingUniformEnvirosuitBrigmedic
    head: ClothingHeadEnvirohelmBrigmedic
    gloves: ClothingHandsGlovesEnviroglovesBlack
