# SPDX-FileCopyrightText: 2020 20kdc <asdd2808@gmail.com>
# SPDX-FileCopyrightText: 2020 AJCM-git <60196617+AJCM-git@users.noreply.github.com>
# SPDX-FileCopyrightText: 2020 FL-OZ <58238103+FL-OZ@users.noreply.github.com>
# SPDX-FileCopyrightText: 2020 FL-OZ <anotherscuffed@gmail.com>
# SPDX-FileCopyrightText: 2020 Hugo Laloge <hugo.laloge@gmail.com>
# SPDX-FileCopyrightText: 2020 Peter Wedder <burneddi@gmail.com>
# SPDX-FileCopyrightText: 2020 VÃ­ctor Aguilera Puerto <zddm@outlook.es>
# SPDX-FileCopyrightText: 2020 ike709 <ike709@users.noreply.github.com>
# SPDX-FileCopyrightText: 2021 Elijahrane <60792108+Elijahrane@users.noreply.github.com>
# SPDX-FileCopyrightText: 2021 Paul Ritter <ritter.paul1@googlemail.com>
# SPDX-FileCopyrightText: 2021 SETh lafuente <cetaciocascarudo@gmail.com>
# SPDX-FileCopyrightText: 2021 SethLafuente <84478872+SethLafuente@users.noreply.github.com>
# SPDX-FileCopyrightText: 2021 Swept <sweptwastaken@protonmail.com>
# SPDX-FileCopyrightText: 2021 Vera Aguilera Puerto <6766154+Zumorica@users.noreply.github.com>
# SPDX-FileCopyrightText: 2022 Kara <lunarautomaton6@gmail.com>
# SPDX-FileCopyrightText: 2022 Leon Friedrich <60421075+ElectroJr@users.noreply.github.com>
# SPDX-FileCopyrightText: 2022 Moony <moonheart08@users.noreply.github.com>
# SPDX-FileCopyrightText: 2022 Morber <14136326+Morb0@users.noreply.github.com>
# SPDX-FileCopyrightText: 2022 Pieter-Jan Briers <pieterjan.briers+git@gmail.com>
# SPDX-FileCopyrightText: 2022 Sissel <axel.roche@pm.me>
# SPDX-FileCopyrightText: 2022 Veritius <veritiusgaming@gmail.com>
# SPDX-FileCopyrightText: 2023 Chief-Engineer <119664036+Chief-Engineer@users.noreply.github.com>
# SPDX-FileCopyrightText: 2023 Debug <49997488+DebugOk@users.noreply.github.com>
# SPDX-FileCopyrightText: 2023 Debug <sidneymaatman@gmail.com>
# SPDX-FileCopyrightText: 2023 DrSmugleaf <DrSmugleaf@users.noreply.github.com>
# SPDX-FileCopyrightText: 2023 Emisse <99158783+Emisse@users.noreply.github.com>
# SPDX-FileCopyrightText: 2023 Fluffiest Floofers <thebluewulf@gmail.com>
# SPDX-FileCopyrightText: 2023 Nemanja <98561806+EmoGarbage404@users.noreply.github.com>
# SPDX-FileCopyrightText: 2023 PrPleGoo <PrPleGoo@users.noreply.github.com>
# SPDX-FileCopyrightText: 2023 coolmankid12345 <55817627+coolmankid12345@users.noreply.github.com>
# SPDX-FileCopyrightText: 2023 coolmankid12345 <coolmankid12345@users.noreply.github.com>
# SPDX-FileCopyrightText: 2023 leo <136020119+leonardo-dabepis@users.noreply.github.com>
# SPDX-FileCopyrightText: 2023 mhamster <81412348+mhamsterr@users.noreply.github.com>
# SPDX-FileCopyrightText: 2023 randy10122 <88034663+randy10122@users.noreply.github.com>
# SPDX-FileCopyrightText: 2024 Colin-Tel <113523727+Colin-Tel@users.noreply.github.com>
# SPDX-FileCopyrightText: 2024 DEATHB4DEFEAT <77995199+DEATHB4DEFEAT@users.noreply.github.com>
# SPDX-FileCopyrightText: 2024 Fansana <116083121+Fansana@users.noreply.github.com>
# SPDX-FileCopyrightText: 2024 Fansana <fansana95@googlemail.com>
# SPDX-FileCopyrightText: 2024 FoxxoTrystan <45297731+FoxxoTrystan@users.noreply.github.com>
# SPDX-FileCopyrightText: 2024 FoxxoTrystan <trystan.garnierhein@gmail.com>
# SPDX-FileCopyrightText: 2024 Nairod <110078045+nairodian@users.noreply.github.com>
# SPDX-FileCopyrightText: 2024 Rane <60792108+Elijahrane@users.noreply.github.com>
# SPDX-FileCopyrightText: 2024 ShatteredSwords <135023515+ShatteredSwords@users.noreply.github.com>
# SPDX-FileCopyrightText: 2024 flyingkarii <flyingkarii@gmail.com>
# SPDX-FileCopyrightText: 2025 Eagle-0 <114363363+Eagle-0@users.noreply.github.com>
# SPDX-FileCopyrightText: 2025 John Willis <143434770+CerberusWolfie@users.noreply.github.com>
# SPDX-FileCopyrightText: 2025 Rosycup <178287475+Rosycup@users.noreply.github.com>
# SPDX-FileCopyrightText: 2025 SixplyDev <einlichen@gmail.com>
# SPDX-FileCopyrightText: 2025 Skubman <ba.fallaria@gmail.com>
# SPDX-FileCopyrightText: 2025 Timfa <timfalken@hotmail.com>
# SPDX-FileCopyrightText: 2025 VMSolidus <evilexecutive@gmail.com>
# SPDX-FileCopyrightText: 2025 sleepyyapril <123355664+sleepyyapril@users.noreply.github.com>
# SPDX-FileCopyrightText: 2025 sleepyyapril <flyingkarii@gmail.com>
#
# SPDX-License-Identifier: AGPL-3.0-or-later AND MIT

- type: job
  id: ResearchDirector
  name: job-name-rd
  description: job-description-rd
  playTimeTracker: JobResearchDirector
  requirements:
    - !type:CharacterPlaytimeRequirement
      tracker: JobChaplain
      min: 14400 # The Den - 4 hour
    - !type:CharacterPlaytimeRequirement
      tracker: JobForensicMantis
      min: 14400 # The Den - 4 hour
    - !type:CharacterDepartmentTimeRequirement
      department: Epistemics # DeltaV - Epistemics Department replacing Science
      min: 28800 # The Den - 8 hour
    - !type:CharacterLogicOrRequirement
      requirements:
        - !type:CharacterSpeciesRequirement
          inverted: true
          species:
            - IPC
        - !type:CharacterTraitRequirement
          traits:
            - AnomalousPositronics
        - !type:CharacterTraitRequirement
          inverted: true
          traits:
            - ShadowkinBlackeye
  weight: 10
  startingGear: ResearchDirectorGear
  icon: "JobIconResearchDirector"
  requireAdminNotify: true
  supervisors: job-supervisors-captain
  canBeAntag: false
  access:
  - Research
  - Command
  - Maintenance
  - ResearchDirector
  - Mantis # DeltaV - Mantis, see Resources/Prototypes/_DV/Access/epistemics.yml
  - Chapel # DeltaV - Chaplain is in Epistemics
  - Robotics # DeltaV - Robotics access
  - External # DeltaV - AI satellite access
  - Cryogenics
  special: # Nyanotrasen - Mystagogue can use the Bible
  - !type:AddComponentSpecial
    components:
    - type: BibleUser # Nyano - Lets them heal with bibles
    - type: Psionic # Nyano - They start with telepathic chat
      powerSlots: 3
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant ]
  - !type:AddComponentSpecial
    components:
      - type: CommandStaff
      - type: InnatePsionicPowers
        powersToAdd:
          - DispelPower
          - MetapsionicPower
          - TelepathyPower
  afterLoadoutSpecial:
  - !type:ModifyEnvirosuitSpecial
    charges: 8
  - !type:ModifyEnvirohelmSpecial
    powerCell: PowerCellMedium

- type: startingGear
  id: ResearchDirectorGear
  subGear:
  - ResearchDirectorPlasmamanGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitResearchDirector
    back: ClothingBackpackResearchDirectorFilled
    shoes: ClothingShoesColorBrown
    id: RnDPDA
    ears: ClothingHeadsetAltScience # Goobstation
    pocket1: BookPsionicsGuidebook
    pocket2: BibleMystagogue
  innerClothingSkirt: ClothingUniformJumpskirtResearchDirector
  satchel: ClothingBackpackSatchelResearchDirectorFilled
  duffelbag: ClothingBackpackDuffelResearchDirectorFilled

- type: startingGear
  id: ResearchDirectorPlasmamanGear
  parent: BasePlasmamanGear
  equipment:
    jumpsuit: ClothingUniformEnvirosuitResearchDirector
    head: ClothingHeadEnvirohelmResearchDirector
    gloves: ClothingHandsGlovesEnviroglovesResearchDirector
