# SPDX-FileCopyrightText: 2020 20kdc
# SPDX-FileCopyrightText: 2020 AJCM-git
# SPDX-FileCopyrightText: 2020 FL-OZ
# SPDX-FileCopyrightText: 2020 Hugo Laloge
# SPDX-FileCopyrightText: 2020 Peter Wedder
# SPDX-FileCopyrightText: 2020 VÃ­ctor Aguilera Puerto
# SPDX-FileCopyrightText: 2020 ike709
# SPDX-FileCopyrightText: 2021 Elijahrane
# SPDX-FileCopyrightText: 2021 Paul Ritter
# SPDX-FileCopyrightText: 2021 SETh lafuente
# SPDX-FileCopyrightText: 2021 SethLafuente
# SPDX-FileCopyrightText: 2021 Swept
# SPDX-FileCopyrightText: 2021 Vera Aguilera Puerto
# SPDX-FileCopyrightText: 2022 Kara
# SPDX-FileCopyrightText: 2022 Leon Friedrich
# SPDX-FileCopyrightText: 2022 Moony
# SPDX-FileCopyrightText: 2022 Morber
# SPDX-FileCopyrightText: 2022 Pieter-Jan Briers
# SPDX-FileCopyrightText: 2022 Sissel
# SPDX-FileCopyrightText: 2022 Veritius
# SPDX-FileCopyrightText: 2023 Chief-Engineer
# SPDX-FileCopyrightText: 2023 Debug
# SPDX-FileCopyrightText: 2023 DrSmugleaf
# SPDX-FileCopyrightText: 2023 Emisse
# SPDX-FileCopyrightText: 2023 Fluffiest Floofers
# SPDX-FileCopyrightText: 2023 Nemanja
# SPDX-FileCopyrightText: 2023 PrPleGoo
# SPDX-FileCopyrightText: 2023 coolmankid12345
# SPDX-FileCopyrightText: 2023 leo
# SPDX-FileCopyrightText: 2023 mhamster
# SPDX-FileCopyrightText: 2023 randy10122
# SPDX-FileCopyrightText: 2024 Colin-Tel
# SPDX-FileCopyrightText: 2024 DEATHB4DEFEAT
# SPDX-FileCopyrightText: 2024 Fansana
# SPDX-FileCopyrightText: 2024 FoxxoTrystan
# SPDX-FileCopyrightText: 2024 Nairod
# SPDX-FileCopyrightText: 2024 Rane
# SPDX-FileCopyrightText: 2024 ShatteredSwords
# SPDX-FileCopyrightText: 2024 flyingkarii
# SPDX-FileCopyrightText: 2025 Eagle-0
# SPDX-FileCopyrightText: 2025 John Willis
# SPDX-FileCopyrightText: 2025 Leonardo
# SPDX-FileCopyrightText: 2025 Rosycup
# SPDX-FileCopyrightText: 2025 SixplyDev
# SPDX-FileCopyrightText: 2025 Skubman
# SPDX-FileCopyrightText: 2025 Timfa
# SPDX-FileCopyrightText: 2025 VMSolidus
# SPDX-FileCopyrightText: 2025 portfiend
# SPDX-FileCopyrightText: 2025 sleepyyapril
#
# SPDX-License-Identifier: AGPL-3.0-or-later AND MIT

- type: job
  id: ResearchDirector
  name: job-name-rd
  description: job-description-rd
  playTimeTracker: JobResearchDirector
  requirements:
    - !type:CharacterPlaytimeRequirement
      tracker: JobChaplain
      min: 14400 # The Den - 4 hour
    - !type:CharacterPlaytimeRequirement
      tracker: JobForensicMantis
      min: 14400 # The Den - 4 hour
    - !type:CharacterDepartmentTimeRequirement
      department: Epistemics # DeltaV - Epistemics Department replacing Science
      min: 28800 # The Den - 8 hour
    - !type:CharacterLogicOrRequirement
      requirements:
      - !type:CharacterSpeciesRequirement
        inverted: true
        species:
        - IPC
      - !type:CharacterTraitRequirement
        traits:
        - AnomalousPositronics
    - !type:CharacterLogicOrRequirement
      requirements:
      - !type:CharacterSpeciesRequirement
        inverted: true
        species:
        - Shadowkin
      - !type:CharacterTraitRequirement
        inverted: true
        traits:
        - ShadowkinBlackeye
  weight: 10
  startingGear: ResearchDirectorGear
  icon: "JobIconResearchDirector"
  requireAdminNotify: true
  supervisors: job-supervisors-captain
  canBeAntag: false
  access:
  - Research
  - Command
  - Maintenance
  - ResearchDirector
  - Mantis # DeltaV - Mantis, see Resources/Prototypes/_DV/Access/epistemics.yml
  - Chapel # DeltaV - Chaplain is in Epistemics
  - Robotics # DeltaV - Robotics access
  - External # DeltaV - AI satellite access
  - Cryogenics
  special: # Nyanotrasen - Mystagogue can use the Bible
  - !type:AddComponentSpecial
    components:
    - type: CommandStaff
    - type: BibleUser # Nyano - Lets them heal with bibles
    - type: Psionic
      powerSlots: 2 # TheDen - This only means that they don't start generating glimmer until they gain a third slot-taking power (they start with Dispel, which takes a slot, and have one no-glimmer slot like all psions)
    - type: InnatePsionicPowers
      powersToAdd: # TheDen - They have one innate slot-taking power, so they need 200 Potentia to gain a new power
        - DispelPower # Takes 1 power slot
        - MetapsionicPower # Doesn't take a power slot
        - TelepathyPower # Doesn't take a power slot
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant ]
  afterLoadoutSpecial:
  - !type:ModifyEnvirosuitSpecial
    charges: 8
  - !type:ModifyEnvirohelmSpecial
    powerCell: PowerCellMedium

- type: startingGear
  id: ResearchDirectorGear
  subGear:
  - ResearchDirectorPlasmamanGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitResearchDirector
    back: ClothingBackpackResearchDirectorFilled
    shoes: ClothingShoesColorBrown
    id: RnDPDA
    ears: ClothingHeadsetAltScience # Goobstation
    pocket1: BookPsionicsGuidebook
    pocket2: HolyBookMystagogue #den- changed item ID
  innerClothingSkirt: ClothingUniformJumpskirtResearchDirector
  satchel: ClothingBackpackSatchelResearchDirectorFilled
  duffelbag: ClothingBackpackDuffelResearchDirectorFilled

- type: startingGear
  id: ResearchDirectorPlasmamanGear
  parent: BasePlasmamanGear
  equipment:
    jumpsuit: ClothingUniformEnvirosuitResearchDirector
    head: ClothingHeadEnvirohelmResearchDirector
    gloves: ClothingHandsGlovesEnviroglovesResearchDirector
