# SPDX-FileCopyrightText: 2023 DrSmugleaf
# SPDX-FileCopyrightText: 2023 Fluffiest Floofers
# SPDX-FileCopyrightText: 2023 Nairod
# SPDX-FileCopyrightText: 2023 PrPleGoo
# SPDX-FileCopyrightText: 2024 DEATHB4DEFEAT
# SPDX-FileCopyrightText: 2024 Fansana
# SPDX-FileCopyrightText: 2024 FoxxoTrystan
# SPDX-FileCopyrightText: 2024 sleepyyapril
# SPDX-FileCopyrightText: 2025 Skubman
# SPDX-FileCopyrightText: 2025 Timfa
# SPDX-FileCopyrightText: 2025 VMSolidus
# SPDX-FileCopyrightText: 2026 MajorMoth
#
# SPDX-License-Identifier: MIT AND AGPL-3.0-or-later

- type: job
  id: SeniorResearcher
  name: job-name-senior-researcher
  description: job-description-senior-researcher
  playTimeTracker: JobSeniorResearcher
  requirements:
    - !type:CharacterDepartmentTimeRequirement
      department: Epistemics # DeltaV - Epistemics Department replacing Science
      min: 360000 # The Den: 100 hrs
  startingGear: SeniorResearcherGear
  icon: "JobIconSeniorResearcher"
  supervisors: job-supervisors-rd
  access:
  - Research
  - Maintenance
  extendedAccess: # DEN: add robotics access to make it inline with scientist
  - Robotics

- type: startingGear
  id: SeniorResearcherGear
  subGear:
  - ScientistPlasmamanGear
  equipment:
    head: ClothingHeadHatBeretRND
    jumpsuit: ClothingUniformJumpsuitSeniorResearcher
    back: ClothingBackpackScienceFilled
    shoes: ClothingShoesColorBlack
    outerClothing: ClothingOuterCoatLabSeniorResearcher
    id: SeniorResearcherPDA
    ears: ClothingHeadsetScience
    pocket1: BookPsionicsGuidebook
  innerClothingSkirt: ClothingUniformJumpskirtSeniorResearcher
  satchel: ClothingBackpackSatchelScienceFilled
  duffelbag: ClothingBackpackDuffelScienceFilled
