# SPDX-FileCopyrightText: 2024 deltanedas
# SPDX-FileCopyrightText: 2025 Eightballll
# SPDX-FileCopyrightText: 2025 sleepyyapril
#
# SPDX-License-Identifier: MIT AND AGPL-3.0-or-later

- type: antag
  id: Dragon
  name: roles-antag-dragon-name
  antagonist: true
  objective: roles-antag-dragon-objective
  requirements: 
    - !type:CharacterOverallTimeRequirement
      min: 36000 #Den - 10 hours
