# SPDX-FileCopyrightText: 2023 Fluffiest Floofers
# SPDX-FileCopyrightText: 2023 deltanedas
# SPDX-FileCopyrightText: 2023 keronshb
# SPDX-FileCopyrightText: 2024 DEATHB4DEFEAT
# SPDX-FileCopyrightText: 2024 Fansana
# SPDX-FileCopyrightText: 2024 FoxxoTrystan
# SPDX-FileCopyrightText: 2024 Leon Friedrich
# SPDX-FileCopyrightText: 2025 Eightballll
# SPDX-FileCopyrightText: 2025 VMSolidus
# SPDX-FileCopyrightText: 2025 sleepyyapril
#
# SPDX-License-Identifier: MIT AND AGPL-3.0-or-later

- type: antag
  id: SpaceNinja
  name: roles-antag-space-ninja-name
  antagonist: true
  setPreference: false
  objective: roles-antag-space-ninja-objective
  requirements: 
  - !type:CharacterOverallTimeRequirement
      min: 36000 #Den - 10 hours
  guides: [ SpaceNinja ]
