# SPDX-FileCopyrightText: 2023 Ed
# SPDX-FileCopyrightText: 2024 FoxxoTrystan
# SPDX-FileCopyrightText: 2024 lapatison
# SPDX-FileCopyrightText: 2025 Eightballll
# SPDX-FileCopyrightText: 2025 sleepyyapril
#
# SPDX-License-Identifier: MIT AND AGPL-3.0-or-later

- type: antag
  id: Thief
  name: roles-antag-thief-name
  antagonist: true
  setPreference: true
  objective: roles-antag-thief-objective
  requirements: 
    - !type:CharacterOverallTimeRequirement
      min: 36000 #Den - 10 hours