# SPDX-FileCopyrightText: 2021 Morbo
# SPDX-FileCopyrightText: 2021 Paul Ritter
# SPDX-FileCopyrightText: 2021 Vera Aguilera Puerto
# SPDX-FileCopyrightText: 2022 Morb
# SPDX-FileCopyrightText: 2023 Fluffiest Floofers
# SPDX-FileCopyrightText: 2024 DEATHB4DEFEAT
# SPDX-FileCopyrightText: 2024 Fansana
# SPDX-FileCopyrightText: 2024 FoxxoTrystan
# SPDX-FileCopyrightText: 2024 Leon Friedrich
# SPDX-FileCopyrightText: 2024 Mr. 27
# SPDX-FileCopyrightText: 2024 sleepyyapril
# SPDX-FileCopyrightText: 2025 Eightballll
# SPDX-FileCopyrightText: 2025 MajorMoth
# SPDX-FileCopyrightText: 2025 Skubman
#
# SPDX-License-Identifier: MIT AND AGPL-3.0-or-later

- type: antag
  id: Traitor
  name: roles-antag-syndicate-agent-name
  antagonist: true
  setPreference: true
  objective: roles-antag-syndicate-agent-objective
  guides: [ Traitors ]
  requirements: 
    - !type:CharacterOverallTimeRequirement
      min: 36000 #Den - 10 hours
      
- type: antag
  id: TraitorSleeper
  name: roles-antag-syndicate-agent-sleeper-name
  antagonist: true
  setPreference: true
  objective: roles-antag-syndicate-agent-sleeper-objective
  requirements: 
    - !type:CharacterOverallTimeRequirement
      min: 36000 #Den - 10 hours

# Syndicate Operative Outfit - Monkey
- type: startingGear
  id: SyndicateOperativeGearMonkey
  equipment:
    head: ClothingHeadHatOutlawHat
    jumpsuit: ClothingUniformJumpsuitOperative
    mask: CigaretteSyndicate

# Syndicate Operative Outfit - Barratry
- type: startingGear
  id: SyndicateOperativeGearExtremelyBasic
  subGear:
  - SyndicatePlasmamanGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitOperative
    back: ClothingBackpackSyndicate
    shoes: ClothingShoesBootsCombatFilled
    gloves: ClothingHandsGlovesColorBlack
  storage:
    back:
    - BoxSurvivalSyndicate
    - WeaponPistolViper
    - PinpointerSyndicateNuclear
    - DeathAcidifierImplanter

#Syndicate Operative Outfit - Basic
- type: startingGear
  id: SyndicateOperativeGearBasic
  parent: SyndicateOperativeGearExtremelyBasic
  equipment:
    ears: ClothingHeadsetAltSyndicate
    gloves: ClothingHandsGlovesCombat
    pocket1: BaseUplinkRadioNukeOps
    id: SyndiPDA
