# SPDX-FileCopyrightText: 2021 Mith-randalf
# SPDX-FileCopyrightText: 2021 Peptide90
# SPDX-FileCopyrightText: 2021 Swept
# SPDX-FileCopyrightText: 2022 Emisse
# SPDX-FileCopyrightText: 2022 Fishfish458
# SPDX-FileCopyrightText: 2022 Kara
# SPDX-FileCopyrightText: 2022 Rane
# SPDX-FileCopyrightText: 2022 fishfish458
# SPDX-FileCopyrightText: 2022 ike709
# SPDX-FileCopyrightText: 2022 theashtronaut
# SPDX-FileCopyrightText: 2023 Adrian16199
# SPDX-FileCopyrightText: 2023 Alekshhh
# SPDX-FileCopyrightText: 2023 Chief-Engineer
# SPDX-FileCopyrightText: 2023 Colin-Tel
# SPDX-FileCopyrightText: 2023 Fluffiest Floofers
# SPDX-FileCopyrightText: 2023 Jeff
# SPDX-FileCopyrightText: 2023 Kevin Zheng
# SPDX-FileCopyrightText: 2023 Kit0vras
# SPDX-FileCopyrightText: 2023 Lei Yunxing
# SPDX-FileCopyrightText: 2023 Nim
# SPDX-FileCopyrightText: 2023 Puro
# SPDX-FileCopyrightText: 2023 Scribbles0
# SPDX-FileCopyrightText: 2023 SpaceCat
# SPDX-FileCopyrightText: 2023 Tad "Taddy" Johnson
# SPDX-FileCopyrightText: 2023 Velcroboy
# SPDX-FileCopyrightText: 2023 Whisper
# SPDX-FileCopyrightText: 2023 metalgearsloth
# SPDX-FileCopyrightText: 2024 Agoichi
# SPDX-FileCopyrightText: 2024 Aviu00
# SPDX-FileCopyrightText: 2024 BonkTrauma
# SPDX-FileCopyrightText: 2024 Flareguy
# SPDX-FileCopyrightText: 2024 FoxxoTrystan
# SPDX-FileCopyrightText: 2024 HappyRoach
# SPDX-FileCopyrightText: 2024 Icepick
# SPDX-FileCopyrightText: 2024 IlyaElDunaev
# SPDX-FileCopyrightText: 2024 LankLTE
# SPDX-FileCopyrightText: 2024 Lonely Fox
# SPDX-FileCopyrightText: 2024 Moomoobeef
# SPDX-FileCopyrightText: 2024 Nairod
# SPDX-FileCopyrightText: 2024 Nemanja
# SPDX-FileCopyrightText: 2024 Plykiya
# SPDX-FileCopyrightText: 2024 PoTeletubby
# SPDX-FileCopyrightText: 2024 SimpleStation14
# SPDX-FileCopyrightText: 2024 Ty Ashley
# SPDX-FileCopyrightText: 2024 Unkn0wn_Gh0st
# SPDX-FileCopyrightText: 2024 crazybrain23
# SPDX-FileCopyrightText: 2024 deltanedas
# SPDX-FileCopyrightText: 2024 kosticia
# SPDX-FileCopyrightText: 2024 lzk
# SPDX-FileCopyrightText: 2024 marbow
# SPDX-FileCopyrightText: 2024 starch
# SPDX-FileCopyrightText: 2024 to4no_fix
# SPDX-FileCopyrightText: 2025 Aiden
# SPDX-FileCopyrightText: 2025 Aidenkrz
# SPDX-FileCopyrightText: 2025 ArtisticRoomba
# SPDX-FileCopyrightText: 2025 Blitz
# SPDX-FileCopyrightText: 2025 BombasterDS2
# SPDX-FileCopyrightText: 2025 BramvanZijp
# SPDX-FileCopyrightText: 2025 Eagle-0
# SPDX-FileCopyrightText: 2025 Fishbait
# SPDX-FileCopyrightText: 2025 Floxington
# SPDX-FileCopyrightText: 2025 GoobBot
# SPDX-FileCopyrightText: 2025 JORJ949
# SPDX-FileCopyrightText: 2025 Jakumba
# SPDX-FileCopyrightText: 2025 Killerqu00
# SPDX-FileCopyrightText: 2025 Lincoln McQueen
# SPDX-FileCopyrightText: 2025 Lumminal
# SPDX-FileCopyrightText: 2025 MajorMoth
# SPDX-FileCopyrightText: 2025 Rosycup
# SPDX-FileCopyrightText: 2025 SX-7
# SPDX-FileCopyrightText: 2025 SX_7
# SPDX-FileCopyrightText: 2025 Solstice
# SPDX-FileCopyrightText: 2025 VMSolidus
# SPDX-FileCopyrightText: 2025 fishbait
# SPDX-FileCopyrightText: 2025 gus
# SPDX-FileCopyrightText: 2025 sleepyyapril
#
# SPDX-License-Identifier: AGPL-3.0-or-later AND MIT

- type: entity
  id: LockerWardenFilledHardsuit
  suffix: Filled, Hardsuit
  parent: LockerWarden
  components:
  - type: StorageFill
    contents:
      - id: FlashlightSeclite
      - id: WeaponDisabler
        prob: 0.3
      - id: ClothingBeltSecurityFilled
      # - id: ClothingHandsGlovesKravMaga # Goobstation - Martial Arts
      - id: Flash
      - id: ClothingEyesGlassesSunglasses
      - id: ClothingHeadsetAltSecurity
      - id: ClothingShoesBootsJack
      - id: ClothingOuterCoatWarden
      - id: ClothingOuterWinterWarden
      - id: ClothingLongcoatWarden # Floofstation
      - id: RubberStampWarden
      - id: DoorRemoteArmory
      - id: ClothingOuterHardsuitCombatWarden # DeltaV - ClothingOuterHardsuitWarden replaced in favour of warden's riot combat hardsuit.
      - id: HoloprojectorSecurity
      - id: ClothingEyesHudSecurity
      - id: BoxPDAPrisoner # Delta-V
      - id: ClothingShoesBootsWinterWarden #Delta V: Add departmental winter boots
      - id: BoxEncryptionKeyPrisoner #Delta-V
      - id: BoxPrisonerHeadset
      - id: LunchboxSecurityFilledRandom # Delta-v Lunchboxes!
        prob: 0.3

- type: entity
  id: LockerWardenFilled
  suffix: Filled
  parent: LockerWarden
  components:
  - type: StorageFill
    contents:
      - id: FlashlightSeclite
      - id: WeaponDisabler
        prob: 0.3
      - id: ClothingBeltSecurityFilled
      - id: ClothingHandsGlovesKravMaga # Goobstation - Martial Arts
      - id: Flash
      - id: ClothingEyesGlassesSunglasses
      - id: ClothingHeadsetAltSecurity
      - id: ClothingShoesBootsJack
      - id: ClothingOuterCoatWarden
      - id: ClothingOuterWinterWarden
      - id: ClothingLongcoatWarden # Floofstation
      - id: RubberStampWarden
      - id: DoorRemoteArmory
      - id: HoloprojectorSecurity
      - id: ClothingEyesHudSecurity
      - id: BoxPDAPrisoner # Delta-V
      - id: ClothingShoesBootsWinterWarden #Delta V: Add departmental winter boots
      - id: BoxEncryptionKeyPrisoner #Delta-V
      - id: BoxPrisonerHeadset
      - id: LunchboxSecurityFilledRandom # Delta-v Lunchboxes!
        prob: 0.3

- type: entity
  id: LockerSecurityFilled
  suffix: Filled
  parent: LockerSecurity
  components:
  - type: StorageFill
    contents:
      - id: FlashlightSeclite
        prob: 0.8
      - id: ClothingUniformJumpsuitSecGrey
        prob: 0.3
      - id: ClothingUniformJumpsuitSecBlue # DeltaV - consistency with other sec uniforms
        prob: 0.3
      - id: ClothingUniformJumpsuitSec # DeltaV - consistency with other sec uniforms
        prob: 0.3
      - id: ClothingUniformJumpskirtSecGrey # DeltaV - consistency with other sec uniforms
        prob: 0.3
      - id: ClothingUniformJumpskirtSecBlue # DeltaV - consistency with other sec uniforms
        prob: 0.3
      - id: ClothingUniformJumpskirtSec # DeltaV - consistency with other sec uniforms
        prob: 0.3
      - id: ClothingHeadHelmetBasic
      - id: ClothingHeadHelmetInsulated # Nyanotrasen - Insulative headgear
        prob: 0.4
      - id: ClothingOuterArmorPlateCarrier # DeltaV - ClothingOuterArmorBasic replaced in favour of plate carrier and stabproof vest
      - id: ClothingOuterArmorDuraVest
      - id: ClothingOuterStasecSweater # DeltaV - in case the officers get cold :3
        prob: 0.75
      - id: ClothingUniformJumpsuitSecFormal # DeltaV - emergency parade time, Central's coming to visit
        prob: 0.25
      - id: ClothingBeltSecurityFilled
      # - id: ClothingBeltCorporateJudo # Goobstation - Martial Arts
      - id: Flash
        prob: 0.5
      - id: ClothingEyesGlassesSunglasses
      - id: ClothingHeadsetAltSecurityRegular # Goobstation
      - id: ClothingHandsGlovesColorBlack
      - id: ClothingShoesBootsJack
      - id: WeaponMeleeNeedle
        prob: 0.1
      - id: ClothingEyesHudSecurity
      - id: HoloprojectorSecurity
        prob: 0.6
      - id: LunchboxSecurityFilledRandom # Delta-v Lunchboxes!
        prob: 0.3

- type: entity
  id: LockerBrigmedicFilled
  suffix: Corpsman, Filled # DeltaV - rename brigmedic to corpsman
  parent: LockerBrigmedic
  components:
  - type: StorageFill
    contents:
      - id: ClothingEyesGlassesCorpsman # DeltaV - Corpsman Glasses
      - id: WeaponDisabler
      - id: TrackingImplanter
        amount: 2
##      - id: ClothingOuterHardsuitCombatCorpsman # DeltaV - ClothingOuterHardsuitBrigmedic replaced in favour of corpsman's combat hardsuit; removing from standard filled locker to place in hardsuit filled locker.
      - id: BoxSterileMask
      - id: BoxLatexGloves # extra ppe
      - id: BoxBodyBag # moved from bag fill
      - id: ClothingHeadHatBeretCorpsman # DeltaV - ClothingHeadHatBeretBrigmedic replaced in favour of corpsman beret.
##      - id: ClothingOuterCoatAMG # DeltaV - removed until I can resprite it or replace it.
      - id: ClothingUniformJumpsuitBrigmedic
      - id: ClothingUniformJumpskirtBrigmedic
##      - id: ClothingUniformJumpskirtOfLife # DeltaV - nah
##        prob: 0.1
      - id: ClothingLongcoatBrigmedic # Floofstation
      - id: MedkitCombatFilled #for when maps don't map in combat kits :<
        # corpsman gets WAY too much medicine, especially when there's medkits mapped into the office. removed all the other random medkits
      - id: LunchboxSecurityFilledRandom # Delta-v Lunchboxes!

# DeltaV - adding corpsman locker w/ hardsuit

- type: entity
  id: LockerBrigmedicFilledHardsuit
  suffix: Corpsman, Filled, Hardsuit
  parent: LockerBrigmedic
  components:
  - type: StorageFill
    contents:
      - id: ClothingEyesGlassesCorpsman # DeltaV - Corpsman Glasses
      - id: WeaponDisabler
      - id: TrackingImplanter
        amount: 2
##      - id: ClothingOuterHardsuitCombatCorpsman # DeltaV - ClothingOuterHardsuitBrigmedic replaced in favour of corpsman's combat hardsuit; removing from standard filled locker to place in hardsuit filled locker.
      - id: BoxSterileMask
      - id: BoxLatexGloves # extra ppe
      - id: BoxBodyBag # moved from bag fill
      - id: ClothingHeadHatBeretCorpsman # DeltaV - ClothingHeadHatBeretBrigmedic replaced in favour of corpsman beret.
##      - id: ClothingOuterCoatAMG # DeltaV - removed until I can resprite it or replace it.
      - id: ClothingUniformJumpsuitBrigmedic
      - id: ClothingUniformJumpskirtBrigmedic
##      - id: ClothingUniformJumpskirtOfLife # DeltaV - nah
##        prob: 0.1
      - id: ClothingLongcoatBrigmedic # Floofstation
      - id: MedkitCombatFilled #for when maps don't map in combat kits :<
        # corpsman gets WAY too much medicine, especially when there's medkits mapped into the office. removed all the other random medkits
      - id: LunchboxSecurityFilledRandom # Delta-v Lunchboxes!
      - id: ClothingOuterHardsuitCombatCorpsman

# DeltaV - end addition

- type: entity
  id: LockerDetectiveFilled
  suffix: Filled
  parent: LockerDetective
  components:
  - type: StorageFill
    contents:
      - id: ClothingEyesHudSecurity
        prob: 0.3
      - id: ClothingHeadHatFedoraBrown
      - id: ClothingNeckTieDet
      - id: ClothingOuterVestDetective
      - id: ClothingOuterCoatDetective
      - id: FlashlightSeclite
      - id: ForensicScanner
      - id: LogProbeCartridge
      - id: BoxForensicPad
      - id: DrinkDetFlask
      - id: ClothingHandsGlovesForensic
      - id: RubberStampDetective
      - id: HoloprojectorSecurity
      - id: BoxEvidenceMarkers
      - id: LunchboxSecurityFilledRandom # Delta-v Lunchboxes!
        prob: 0.3
      - id: HandLabeler
      - id: BoxTapeRecorder # DeltaV

- type: entity
  id: ClosetBombFilled
  parent: ClosetBomb
  suffix: Filled
  components:
  - type: StorageFill
    contents:
      - id: ClothingHeadHelmetBombSuit
      - id: ClothingOuterSuitBomb
      # NT is cheap, what can you do...
      - id: Wirecutter
        prob: 0.9
      - id: Screwdriver
        prob: 0.9
      - id: Multitool
        prob: 0.5

- type: entity
  parent: GunSafe
  id: GunSafeDisabler
  name: disabler safe
  components:
  - type: StorageFill
    contents:
    - id: WeaponDisabler
      amount: 5

- type: entity
  parent: GunSafe
  id: GunSafePistolMk58
  name: mk58 safe
  components:
  - type: StorageFill
    contents:
    - id: WeaponPistolMk58
      amount: 4
    - id: MagazinePistol
      amount: 8

- type: entity
  parent: GunSafe
  id: GunSafeRifleLecter
  name: lecter safe
  components:
  - type: StorageFill
    contents:
    - id: WeaponRifleLecter
      amount: 2
    - id: MagazineRifle
      amount: 4

- type: entity
  parent: GunSafe
  id: GunSafeSubMachineGunDrozd
  name: drozd safe
  components:
  - type: StorageFill
    contents:
    - id: WeaponSubMachineGunDrozd
      amount: 2
    - id: MagazinePistolSubMachineGun
      amount: 4

- type: entity
  parent: GunSafe
  id: GunSafeShotgunEnforcer
  name: enforcer safe
  components:
  - type: StorageFill
    contents:
    - id: WeaponShotgunEnforcer
      amount: 2
    - id: MagazineShotgun
      amount: 4

- type: entity
  parent: GunSafe
  id: GunSafeShotgunKammerer
  name: kammerer safe
  components:
  - type: StorageFill
    contents:
    - id: WeaponShotgunKammerer
      amount: 2
    - id: MagazineShotgun
      amount: 4

- type: entity
  id: GunSafeSubMachineGunWt550
  suffix: WT550
  parent: GunSafe
  name: wt550 safe
  components:
  - type: StorageFill
    contents:
    - id: WeaponSubMachineGunWt550
      amount: 2
    - id: MagazinePistolSubMachineGunTopMounted
      amount: 4

- type: entity
  parent: GunSafe
  id: GunSafeLaserCarbine
  name: laser safe
  components:
  - type: StorageFill
    contents:
    - id: WeaponLaserCarbine
      amount: 3

- type: entity
  id: GunSafeRifleBRDIR25
  suffix: BRDI-R25
  parent: GunSafe
  name: BRDI-R25 safe
  components:
  - type: StorageFill
    contents:
    - id: WeaponSubMachineGunBRDIR25
      amount: 2
    - id: MagazineCaselessRifle
      amount: 4
