# SPDX-FileCopyrightText: 2023 Colin-Tel
# SPDX-FileCopyrightText: 2023 Fluffiest Floofers
# SPDX-FileCopyrightText: 2024 Adrian16199
# SPDX-FileCopyrightText: 2024 DEATHB4DEFEAT
# SPDX-FileCopyrightText: 2024 Fansana
# SPDX-FileCopyrightText: 2024 FoxxoTrystan
# SPDX-FileCopyrightText: 2024 Rane
# SPDX-FileCopyrightText: 2024 ShatteredSwords
# SPDX-FileCopyrightText: 2025 Rosycup
# SPDX-FileCopyrightText: 2025 Shaman
# SPDX-FileCopyrightText: 2025 SixplyDev
# SPDX-FileCopyrightText: 2025 Skubman
# SPDX-FileCopyrightText: 2025 Steven Higginbotham
# SPDX-FileCopyrightText: 2025 Timfa
# SPDX-FileCopyrightText: 2025 VMSolidus
# SPDX-FileCopyrightText: 2025 sleepyyapril
# SPDX-FileCopyrightText: 2026 Dirius77
#
# SPDX-License-Identifier: AGPL-3.0-or-later AND MIT

- type: job
  id: ForensicMantis
  name: job-name-mantis
  description: job-description-mantis
  playTimeTracker: JobForensicMantis
  requirements:
    - !type:CharacterOverallTimeRequirement
      min: 18000
    - !type:CharacterDepartmentTimeRequirement
      department: Epistemics # DeltaV - Epistemics Department replacing Science
      min: 3600
    - !type:CharacterLogicOrRequirement
      requirements:
        - !type:CharacterSpeciesRequirement
          inverted: true
          species:
            - IPC
        - !type:CharacterTraitRequirement
          traits:
            - AnomalousPositronics
    - !type:CharacterLogicOrRequirement
      requirements:
        - !type:CharacterSpeciesRequirement
          inverted: true
          species:
          - Shadowkin
        - !type:CharacterTraitRequirement
          inverted: true
          traits:
            - ShadowkinBlackeye
  startingGear: MantisGearStarter # TheDen
  icon: "JobIconForensicMantis"
  supervisors: job-supervisors-rd
  canBeAntag: true # DeltaV - Mantis is no longer a Detective
  # whitelistRequired: true
  access:
  - Research
  - Maintenance
  - Mantis # DeltaV - Mantis, see Resources/Prototypes/_DV/Access/epistemics.yml
  special:
  - !type:AddComponentSpecial
    components:
    - type: Psionic
      powerSlots: 1 # TheDen - This only means that they don't start generating glimmer until they gain a second slot-taking power (they have one no-glimmer slot like all psions)
    - type: InnatePsionicPowers
      powersToAdd: # TheDen - They have no innate slot-taking powers, so they need 100 Potentia to gain a new power
        - MetapsionicPower # Doesn't take a power slot
        - TelepathyPower # Doesn't take a power slot
        - PsychognomyPower # TheDen - Doesn't take a power slot (and the psionic monitor should get a little extra information for roleplay)
        - AssayPower # Doesn't take a power slot

- type: startingGear
  id: MantisGearStarter # TheDen
  subGear:
  - MantisPlasmamanGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitMantisDark # TheDen
    back: ClothingBackpackMantis # TheDen - Nothing to fill it with anymore
    shoes: ClothingShoesSandalsMantisDark # TheDen
    head: ClothingHeadHoodMantisDark # TheDen
    id: ForensicMantisPDA
    eyes: ClothingEyesHudEpistemicsMantis # TheDen
    ears: ClothingHeadsetMantis # TheDen
    gloves: ClothingHandsGlovesMantisDark # TheDen
    outerClothing: ClothingOuterWinterCoatMantisDarkFolded # TheDen
    belt: ClothingBeltMantisDark # TheDen
    # pocket1: BookPsionicsGuidebook # TheDen - Throwing this in their locker because it sucks
    pocket1: HandheldPsionicsRegistry # TheDen
  innerClothingSkirt: ClothingUniformSkirtMantisAiry # TheDen
  satchel: ClothingBackpackSatchelMantis # TheDen - Nothing to fill it with anymore
  duffelbag: ClothingBackpackDuffelMantis # TheDen - Nothing to fill it with anymore

- type: startingGear
  id: MantisPlasmamanGear
  parent: BasePlasmamanGear
  equipment:
    jumpsuit: ClothingUniformEnvirosuitMantis
    head: ClothingHeadEnvirohelmMantis
    gloves: ClothingHandsGlovesEnviroglovesBlack # TheDen
