# SPDX-FileCopyrightText: 2020 ComicIronic
# SPDX-FileCopyrightText: 2020 Tyler Young
# SPDX-FileCopyrightText: 2020 Ygg01
# SPDX-FileCopyrightText: 2021 Javier Guardia Fern√°ndez
# SPDX-FileCopyrightText: 2021 Swept
# SPDX-FileCopyrightText: 2021 Vera Aguilera Puerto
# SPDX-FileCopyrightText: 2021 mirrorcult
# SPDX-FileCopyrightText: 2022 0x6273
# SPDX-FileCopyrightText: 2022 Kara D
# SPDX-FileCopyrightText: 2022 Zoldorf
# SPDX-FileCopyrightText: 2022 wrexbe
# SPDX-FileCopyrightText: 2023 DrSmugleaf
# SPDX-FileCopyrightText: 2023 Leon Friedrich
# SPDX-FileCopyrightText: 2023 Moony
# SPDX-FileCopyrightText: 2023 Pieter-Jan Briers
# SPDX-FileCopyrightText: 2023 metalgearsloth
# SPDX-FileCopyrightText: 2024 DEATHB4DEFEAT
# SPDX-FileCopyrightText: 2024 Debug
# SPDX-FileCopyrightText: 2025 MajorMoth
# SPDX-FileCopyrightText: 2025 VMSolidus
# SPDX-FileCopyrightText: 2025 sleepyyapril
#
# SPDX-License-Identifier: AGPL-3.0-or-later AND MIT

name: Build & Test Debug

concurrency:
  group: debug_build_test-pr${{ github.event.pull_request.number }}
  cancel-in-progress: true # we don't want to clog up the queue by making changes to a PR

on:
  push:
    branches: [ master, staging, trying ]
  merge_group:
  pull_request:
    types: [ opened, reopened, synchronize, ready_for_review ]
    branches: [ master ]

jobs:
  build:
    if: github.actor != 'TheDen-Bot' && github.event.pull_request.draft == false
    #strategy: # using a single self-hosted runner, this will not be needed anytime soon
    #  matrix:
    #    os: [ubuntu-latest]

    runs-on: self-hosted

    steps:
    - name: Checkout Master
      uses: actions/checkout@v3.6.0

    - name: Setup Submodule
      run: |
        git submodule update --init --recursive

    - name: Pull engine updates
      uses: space-wizards/submodule-dependency@v0.1.5

    - name: Update Engine Submodules
      run: |
        cd RobustToolbox/
        git submodule update --init --recursive

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v3.2.0
      with:
        dotnet-version: 9.0.x

    - name: Install dependencies
      run: ionice -c2 -n7 nice -n19 taskset -c 0-5 dotnet restore

    - name: Build Project
      run: ionice -c2 -n7 nice -n19 taskset -c 0-5 dotnet build --configuration DebugOpt --no-restore /p:WarningsAsErrors=nullable /m

    - name: Run Content.Tests
      run: ionice -c2 -n7 nice -n19 taskset -c 0-5 dotnet test --no-build --configuration DebugOpt Content.Tests/Content.Tests.csproj -- NUnit.ConsoleOut=0

    - name: Run Content.IntegrationTests
      run: |
        export DOTNET_gcServer=1
        ionice -c2 -n7 nice -n19 taskset -c 0-5 dotnet test --no-build --configuration DebugOpt Content.IntegrationTests/Content.IntegrationTests.csproj -- NUnit.ConsoleOut=0

  ci-success:
    name: Build & Test Debug
    needs:
      - build
    runs-on: ubuntu-latest
    steps:
      - name: CI succeeded
        run: exit 0
