# SPDX-FileCopyrightText: 2022 Paul Ritter <ritter.paul1@googlemail.com>
# SPDX-FileCopyrightText: 2025 sleepyyapril <123355664+sleepyyapril@users.noreply.github.com>
#
# SPDX-License-Identifier: AGPL-3.0-or-later AND MIT

name: No submodule update checker

on:
  pull_request:
    paths:
      - 'RobustToolbox'

jobs:
  this_aint_right:
    if: github.actor != 'sleepyyapril' || github.actor != 'ZigTag'
    name: Submodule update in pr found
    runs-on: ubuntu-latest
    steps:
      - name: Fail
        run: exit 1
